// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budget.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addBudgetPerson = `-- name: AddBudgetPerson :one
INSERT INTO budget_to_user_mapping (budget_id, user_name, user_id)
VALUES ($1, $2, $3)
RETURNING id, budget_id, user_name, user_id
`

type AddBudgetPersonParams struct {
	BudgetID uuid.UUID  `json:"budget_id"`
	UserName *string    `json:"user_name"`
	UserID   *uuid.UUID `json:"user_id"`
}

func (q *Queries) AddBudgetPerson(ctx context.Context, arg AddBudgetPersonParams) (BudgetToUserMapping, error) {
	row := q.db.QueryRow(ctx, addBudgetPerson, arg.BudgetID, arg.UserName, arg.UserID)
	var i BudgetToUserMapping
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.UserName,
		&i.UserID,
	)
	return i, err
}

const addIncomeEntry = `-- name: AddIncomeEntry :one
INSERT INTO income_to_budget_mapping (budget_id, name, amount, recurring, budget_person_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, budget_id, user_id, name, amount, recurring, budget_person_id
`

type AddIncomeEntryParams struct {
	BudgetID       uuid.UUID      `json:"budget_id"`
	Name           *string        `json:"name"`
	Amount         pgtype.Numeric `json:"amount"`
	Recurring      bool           `json:"recurring"`
	BudgetPersonID *int32         `json:"budget_person_id"`
}

func (q *Queries) AddIncomeEntry(ctx context.Context, arg AddIncomeEntryParams) (IncomeToBudgetMapping, error) {
	row := q.db.QueryRow(ctx, addIncomeEntry,
		arg.BudgetID,
		arg.Name,
		arg.Amount,
		arg.Recurring,
		arg.BudgetPersonID,
	)
	var i IncomeToBudgetMapping
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.UserID,
		&i.Name,
		&i.Amount,
		&i.Recurring,
		&i.BudgetPersonID,
	)
	return i, err
}

const createBudget = `-- name: CreateBudget :one
INSERT INTO budget (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, start_date, end_date, active
`

type CreateBudgetParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget, arg.UserID, arg.Name)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Active,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budget
WHERE id = $1
`

func (q *Queries) DeleteBudget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBudget, id)
	return err
}

const deleteIncomeEntry = `-- name: DeleteIncomeEntry :exec
DELETE FROM income_to_budget_mapping
WHERE id = $1 AND budget_id = $2
`

type DeleteIncomeEntryParams struct {
	ID       int32     `json:"id"`
	BudgetID uuid.UUID `json:"budget_id"`
}

func (q *Queries) DeleteIncomeEntry(ctx context.Context, arg DeleteIncomeEntryParams) error {
	_, err := q.db.Exec(ctx, deleteIncomeEntry, arg.ID, arg.BudgetID)
	return err
}

const existsBudgetByNameAndUser = `-- name: ExistsBudgetByNameAndUser :one
SELECT EXISTS (
    SELECT 1 FROM budget WHERE name = $1 AND user_id = $2
) AS exists
`

type ExistsBudgetByNameAndUserParams struct {
	Name   string    `json:"name"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ExistsBudgetByNameAndUser(ctx context.Context, arg ExistsBudgetByNameAndUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsBudgetByNameAndUser, arg.Name, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsBudgetPerson = `-- name: ExistsBudgetPerson :one
SELECT EXISTS (
    SELECT 1 FROM budget_to_user_mapping WHERE budget_id = $1 AND user_name = $2
) AS exists
`

type ExistsBudgetPersonParams struct {
	BudgetID uuid.UUID `json:"budget_id"`
	UserName *string   `json:"user_name"`
}

func (q *Queries) ExistsBudgetPerson(ctx context.Context, arg ExistsBudgetPersonParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsBudgetPerson, arg.BudgetID, arg.UserName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT id, user_id, name, start_date, end_date, active
FROM budget
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBudgetByID(ctx context.Context, id uuid.UUID) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByID, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Active,
	)
	return i, err
}

const listBudgetPeople = `-- name: ListBudgetPeople :many
SELECT id, budget_id, user_name, user_id
FROM budget_to_user_mapping
WHERE budget_id = $1
ORDER BY id
`

func (q *Queries) ListBudgetPeople(ctx context.Context, budgetID uuid.UUID) ([]BudgetToUserMapping, error) {
	rows, err := q.db.Query(ctx, listBudgetPeople, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetToUserMapping
	for rows.Next() {
		var i BudgetToUserMapping
		if err := rows.Scan(
			&i.ID,
			&i.BudgetID,
			&i.UserName,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetsByUser = `-- name: ListBudgetsByUser :many
SELECT id, user_id, name, start_date, end_date, active
FROM budget
WHERE user_id = $1
ORDER BY active DESC, name
`

func (q *Queries) ListBudgetsByUser(ctx context.Context, userID uuid.UUID) ([]Budget, error) {
	rows, err := q.db.Query(ctx, listBudgetsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeEntries = `-- name: ListIncomeEntries :many
SELECT id, budget_id, user_id, name, amount, recurring, budget_person_id
FROM income_to_budget_mapping
WHERE budget_id = $1
ORDER BY id
`

func (q *Queries) ListIncomeEntries(ctx context.Context, budgetID uuid.UUID) ([]IncomeToBudgetMapping, error) {
	rows, err := q.db.Query(ctx, listIncomeEntries, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncomeToBudgetMapping
	for rows.Next() {
		var i IncomeToBudgetMapping
		if err := rows.Scan(
			&i.ID,
			&i.BudgetID,
			&i.UserID,
			&i.Name,
			&i.Amount,
			&i.Recurring,
			&i.BudgetPersonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBudgetPerson = `-- name: RemoveBudgetPerson :exec
DELETE FROM budget_to_user_mapping
WHERE id = $1 AND budget_id = $2
`

type RemoveBudgetPersonParams struct {
	ID       int32     `json:"id"`
	BudgetID uuid.UUID `json:"budget_id"`
}

func (q *Queries) RemoveBudgetPerson(ctx context.Context, arg RemoveBudgetPersonParams) error {
	_, err := q.db.Exec(ctx, removeBudgetPerson, arg.ID, arg.BudgetID)
	return err
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budget
SET name = $2, active = $3
WHERE id = $1
RETURNING id, user_id, name, start_date, end_date, active
`

type UpdateBudgetParams struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Active bool      `json:"active"`
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudget, arg.ID, arg.Name, arg.Active)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Active,
	)
	return i, err
}

const updateIncomeEntry = `-- name: UpdateIncomeEntry :one
UPDATE income_to_budget_mapping
SET name = $3, amount = $4, recurring = $5, budget_person_id = $6
WHERE id = $1 AND budget_id = $2
RETURNING id, budget_id, user_id, name, amount, recurring, budget_person_id
`

type UpdateIncomeEntryParams struct {
	ID             int32          `json:"id"`
	BudgetID       uuid.UUID      `json:"budget_id"`
	Name           *string        `json:"name"`
	Amount         pgtype.Numeric `json:"amount"`
	Recurring      bool           `json:"recurring"`
	BudgetPersonID *int32         `json:"budget_person_id"`
}

func (q *Queries) UpdateIncomeEntry(ctx context.Context, arg UpdateIncomeEntryParams) (IncomeToBudgetMapping, error) {
	row := q.db.QueryRow(ctx, updateIncomeEntry,
		arg.ID,
		arg.BudgetID,
		arg.Name,
		arg.Amount,
		arg.Recurring,
		arg.BudgetPersonID,
	)
	var i IncomeToBudgetMapping
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.UserID,
		&i.Name,
		&i.Amount,
		&i.Recurring,
		&i.BudgetPersonID,
	)
	return i, err
}
