// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budget_profile.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addBudgetPersonToProfile = `-- name: AddBudgetPersonToProfile :one

INSERT INTO budget_to_profile_mapping (budget_profile_id, user_name, user_id, color, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, budget_profile_id, user_name, user_id, is_active, color, role
`

type AddBudgetPersonToProfileParams struct {
	BudgetProfileID uuid.UUID  `json:"budget_profile_id"`
	UserName        *string    `json:"user_name"`
	UserID          *uuid.UUID `json:"user_id"`
	Color           string     `json:"color"`
	Role            string     `json:"role"`
}

// ── People ────────────────────────────────────────────────────────────────────
func (q *Queries) AddBudgetPersonToProfile(ctx context.Context, arg AddBudgetPersonToProfileParams) (BudgetToProfileMapping, error) {
	row := q.db.QueryRow(ctx, addBudgetPersonToProfile,
		arg.BudgetProfileID,
		arg.UserName,
		arg.UserID,
		arg.Color,
		arg.Role,
	)
	var i BudgetToProfileMapping
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.UserName,
		&i.UserID,
		&i.IsActive,
		&i.Color,
		&i.Role,
	)
	return i, err
}

const addIncomeSource = `-- name: AddIncomeSource :one

INSERT INTO income_source (budget_profile_id, budget_person_id, name, income_type, default_amount, recurring, payment_frequency, before_tax)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, budget_profile_id, budget_person_id, name, income_type, default_amount, recurring, created_at, payment_frequency, before_tax
`

type AddIncomeSourceParams struct {
	BudgetProfileID  uuid.UUID      `json:"budget_profile_id"`
	BudgetPersonID   *int32         `json:"budget_person_id"`
	Name             string         `json:"name"`
	IncomeType       string         `json:"income_type"`
	DefaultAmount    pgtype.Numeric `json:"default_amount"`
	Recurring        bool           `json:"recurring"`
	PaymentFrequency string         `json:"payment_frequency"`
	BeforeTax        bool           `json:"before_tax"`
}

// ── Income Sources ────────────────────────────────────────────────────────────
func (q *Queries) AddIncomeSource(ctx context.Context, arg AddIncomeSourceParams) (IncomeSource, error) {
	row := q.db.QueryRow(ctx, addIncomeSource,
		arg.BudgetProfileID,
		arg.BudgetPersonID,
		arg.Name,
		arg.IncomeType,
		arg.DefaultAmount,
		arg.Recurring,
		arg.PaymentFrequency,
		arg.BeforeTax,
	)
	var i IncomeSource
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.BudgetPersonID,
		&i.Name,
		&i.IncomeType,
		&i.DefaultAmount,
		&i.Recurring,
		&i.CreatedAt,
		&i.PaymentFrequency,
		&i.BeforeTax,
	)
	return i, err
}

const addSavingsSource = `-- name: AddSavingsSource :one

INSERT INTO savings_source (budget_profile_id, budget_person_id, name, amount, frequency, payment_method_id, payment_days)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, budget_profile_id, budget_person_id, name, amount, frequency, created_at, is_tax_reserve, federal_amount, state_amount, payment_method_id, payment_days
`

type AddSavingsSourceParams struct {
	BudgetProfileID uuid.UUID      `json:"budget_profile_id"`
	BudgetPersonID  *int32         `json:"budget_person_id"`
	Name            string         `json:"name"`
	Amount          pgtype.Numeric `json:"amount"`
	Frequency       string         `json:"frequency"`
	PaymentMethodID *uuid.UUID     `json:"payment_method_id"`
	PaymentDays     []int32        `json:"payment_days"`
}

// ── Savings Sources ───────────────────────────────────────────────────────────
func (q *Queries) AddSavingsSource(ctx context.Context, arg AddSavingsSourceParams) (SavingsSource, error) {
	row := q.db.QueryRow(ctx, addSavingsSource,
		arg.BudgetProfileID,
		arg.BudgetPersonID,
		arg.Name,
		arg.Amount,
		arg.Frequency,
		arg.PaymentMethodID,
		arg.PaymentDays,
	)
	var i SavingsSource
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.BudgetPersonID,
		&i.Name,
		&i.Amount,
		&i.Frequency,
		&i.CreatedAt,
		&i.IsTaxReserve,
		&i.FederalAmount,
		&i.StateAmount,
		&i.PaymentMethodID,
		&i.PaymentDays,
	)
	return i, err
}

const createBudgetPeriod = `-- name: CreateBudgetPeriod :one

INSERT INTO budget_period (budget_profile_id, start_date, end_date)
VALUES ($1, $2, $3)
RETURNING id, budget_profile_id, start_date, end_date, is_archived, created_at
`

type CreateBudgetPeriodParams struct {
	BudgetProfileID uuid.UUID   `json:"budget_profile_id"`
	StartDate       pgtype.Date `json:"start_date"`
	EndDate         pgtype.Date `json:"end_date"`
}

// ── BudgetPeriod ──────────────────────────────────────────────────────────────
func (q *Queries) CreateBudgetPeriod(ctx context.Context, arg CreateBudgetPeriodParams) (BudgetPeriod, error) {
	row := q.db.QueryRow(ctx, createBudgetPeriod, arg.BudgetProfileID, arg.StartDate, arg.EndDate)
	var i BudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.StartDate,
		&i.EndDate,
		&i.IsArchived,
		&i.CreatedAt,
	)
	return i, err
}

const createBudgetProfile = `-- name: CreateBudgetProfile :one

INSERT INTO budget_profile (user_id, name, cycle, country_code)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, cycle, created_at, country_code
`

type CreateBudgetProfileParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Name        string    `json:"name"`
	Cycle       string    `json:"cycle"`
	CountryCode *string   `json:"country_code"`
}

// ── BudgetProfile ─────────────────────────────────────────────────────────────
func (q *Queries) CreateBudgetProfile(ctx context.Context, arg CreateBudgetProfileParams) (BudgetProfile, error) {
	row := q.db.QueryRow(ctx, createBudgetProfile,
		arg.UserID,
		arg.Name,
		arg.Cycle,
		arg.CountryCode,
	)
	var i BudgetProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Cycle,
		&i.CreatedAt,
		&i.CountryCode,
	)
	return i, err
}

const createIncomeEntry = `-- name: CreateIncomeEntry :one

INSERT INTO income_entry (budget_period_id, income_source_id, budget_person_id, name, amount)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, budget_period_id, income_source_id, budget_person_id, name, amount, created_at
`

type CreateIncomeEntryParams struct {
	BudgetPeriodID uuid.UUID      `json:"budget_period_id"`
	IncomeSourceID *int32         `json:"income_source_id"`
	BudgetPersonID *int32         `json:"budget_person_id"`
	Name           *string        `json:"name"`
	Amount         pgtype.Numeric `json:"amount"`
}

// ── Income Entries ────────────────────────────────────────────────────────────
func (q *Queries) CreateIncomeEntry(ctx context.Context, arg CreateIncomeEntryParams) (IncomeEntry, error) {
	row := q.db.QueryRow(ctx, createIncomeEntry,
		arg.BudgetPeriodID,
		arg.IncomeSourceID,
		arg.BudgetPersonID,
		arg.Name,
		arg.Amount,
	)
	var i IncomeEntry
	err := row.Scan(
		&i.ID,
		&i.BudgetPeriodID,
		&i.IncomeSourceID,
		&i.BudgetPersonID,
		&i.Name,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBudgetProfile = `-- name: DeleteBudgetProfile :exec
DELETE FROM budget_profile WHERE id = $1
`

func (q *Queries) DeleteBudgetProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBudgetProfile, id)
	return err
}

const deleteIncomeSource = `-- name: DeleteIncomeSource :exec
DELETE FROM income_source WHERE id = $1 AND budget_profile_id = $2
`

type DeleteIncomeSourceParams struct {
	ID              int32     `json:"id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

func (q *Queries) DeleteIncomeSource(ctx context.Context, arg DeleteIncomeSourceParams) error {
	_, err := q.db.Exec(ctx, deleteIncomeSource, arg.ID, arg.BudgetProfileID)
	return err
}

const deleteSavingsSource = `-- name: DeleteSavingsSource :exec
DELETE FROM savings_source WHERE id = $1 AND budget_profile_id = $2
`

type DeleteSavingsSourceParams struct {
	ID              int32     `json:"id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

func (q *Queries) DeleteSavingsSource(ctx context.Context, arg DeleteSavingsSourceParams) error {
	_, err := q.db.Exec(ctx, deleteSavingsSource, arg.ID, arg.BudgetProfileID)
	return err
}

const deleteTaxReserveSavingsSource = `-- name: DeleteTaxReserveSavingsSource :exec
DELETE FROM savings_source WHERE budget_profile_id = $1 AND is_tax_reserve = TRUE
`

func (q *Queries) DeleteTaxReserveSavingsSource(ctx context.Context, budgetProfileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaxReserveSavingsSource, budgetProfileID)
	return err
}

const existsBudgetPersonForUser = `-- name: ExistsBudgetPersonForUser :one
SELECT EXISTS (
    SELECT 1 FROM budget_to_profile_mapping
    WHERE budget_profile_id = $1::uuid AND user_id = $2::uuid AND is_active = TRUE
) AS exists
`

type ExistsBudgetPersonForUserParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
}

func (q *Queries) ExistsBudgetPersonForUser(ctx context.Context, arg ExistsBudgetPersonForUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsBudgetPersonForUser, arg.Column1, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsBudgetPersonInProfile = `-- name: ExistsBudgetPersonInProfile :one
SELECT EXISTS (
    SELECT 1 FROM budget_to_profile_mapping
    WHERE budget_profile_id = $1::uuid AND user_name = $2 AND is_active = TRUE
) AS exists
`

type ExistsBudgetPersonInProfileParams struct {
	Column1  uuid.UUID `json:"column_1"`
	UserName *string   `json:"user_name"`
}

func (q *Queries) ExistsBudgetPersonInProfile(ctx context.Context, arg ExistsBudgetPersonInProfileParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsBudgetPersonInProfile, arg.Column1, arg.UserName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsBudgetProfileByNameAndUser = `-- name: ExistsBudgetProfileByNameAndUser :one
SELECT EXISTS (
    SELECT 1 FROM budget_profile WHERE name = $1 AND user_id = $2
) AS exists
`

type ExistsBudgetProfileByNameAndUserParams struct {
	Name   string    `json:"name"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ExistsBudgetProfileByNameAndUser(ctx context.Context, arg ExistsBudgetProfileByNameAndUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsBudgetProfileByNameAndUser, arg.Name, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getBudgetPeriodByDate = `-- name: GetBudgetPeriodByDate :one
SELECT id, budget_profile_id, start_date, end_date, is_archived, created_at
FROM budget_period
WHERE budget_profile_id = $1
  AND start_date <= $2::date
  AND end_date >= $2::date
ORDER BY start_date DESC
LIMIT 1
`

type GetBudgetPeriodByDateParams struct {
	BudgetProfileID uuid.UUID   `json:"budget_profile_id"`
	Column2         pgtype.Date `json:"column_2"`
}

// Returns the budget period containing a given date for a specific profile.
// Used by the Plaid sync job to route imported transactions to the right period.
func (q *Queries) GetBudgetPeriodByDate(ctx context.Context, arg GetBudgetPeriodByDateParams) (BudgetPeriod, error) {
	row := q.db.QueryRow(ctx, getBudgetPeriodByDate, arg.BudgetProfileID, arg.Column2)
	var i BudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.StartDate,
		&i.EndDate,
		&i.IsArchived,
		&i.CreatedAt,
	)
	return i, err
}

const getBudgetPeriodByID = `-- name: GetBudgetPeriodByID :one
SELECT id, budget_profile_id, start_date, end_date, is_archived, created_at
FROM budget_period
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBudgetPeriodByID(ctx context.Context, id uuid.UUID) (BudgetPeriod, error) {
	row := q.db.QueryRow(ctx, getBudgetPeriodByID, id)
	var i BudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.StartDate,
		&i.EndDate,
		&i.IsArchived,
		&i.CreatedAt,
	)
	return i, err
}

const getBudgetPersonByProfileID = `-- name: GetBudgetPersonByProfileID :one
SELECT id, budget_profile_id, user_name, user_id, is_active, color, role
FROM budget_to_profile_mapping
WHERE id = $1 AND budget_profile_id = $2
LIMIT 1
`

type GetBudgetPersonByProfileIDParams struct {
	ID              int32     `json:"id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

func (q *Queries) GetBudgetPersonByProfileID(ctx context.Context, arg GetBudgetPersonByProfileIDParams) (BudgetToProfileMapping, error) {
	row := q.db.QueryRow(ctx, getBudgetPersonByProfileID, arg.ID, arg.BudgetProfileID)
	var i BudgetToProfileMapping
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.UserName,
		&i.UserID,
		&i.IsActive,
		&i.Color,
		&i.Role,
	)
	return i, err
}

const getBudgetPersonByUserID = `-- name: GetBudgetPersonByUserID :one
SELECT id, budget_profile_id, user_name, user_id, is_active, color, role
FROM budget_to_profile_mapping
WHERE budget_profile_id = $1 AND user_id = $2 AND is_active = TRUE
LIMIT 1
`

type GetBudgetPersonByUserIDParams struct {
	BudgetProfileID uuid.UUID  `json:"budget_profile_id"`
	UserID          *uuid.UUID `json:"user_id"`
}

func (q *Queries) GetBudgetPersonByUserID(ctx context.Context, arg GetBudgetPersonByUserIDParams) (BudgetToProfileMapping, error) {
	row := q.db.QueryRow(ctx, getBudgetPersonByUserID, arg.BudgetProfileID, arg.UserID)
	var i BudgetToProfileMapping
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.UserName,
		&i.UserID,
		&i.IsActive,
		&i.Color,
		&i.Role,
	)
	return i, err
}

const getBudgetProfileByID = `-- name: GetBudgetProfileByID :one
SELECT id, user_id, name, cycle, created_at, country_code
FROM budget_profile
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBudgetProfileByID(ctx context.Context, id uuid.UUID) (BudgetProfile, error) {
	row := q.db.QueryRow(ctx, getBudgetProfileByID, id)
	var i BudgetProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Cycle,
		&i.CreatedAt,
		&i.CountryCode,
	)
	return i, err
}

const getLatestBudgetPeriod = `-- name: GetLatestBudgetPeriod :one
SELECT id, budget_profile_id, start_date, end_date, is_archived, created_at
FROM budget_period
WHERE budget_profile_id = $1
ORDER BY start_date DESC
LIMIT 1
`

func (q *Queries) GetLatestBudgetPeriod(ctx context.Context, budgetProfileID uuid.UUID) (BudgetPeriod, error) {
	row := q.db.QueryRow(ctx, getLatestBudgetPeriod, budgetProfileID)
	var i BudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.StartDate,
		&i.EndDate,
		&i.IsArchived,
		&i.CreatedAt,
	)
	return i, err
}

const getSavingsSource = `-- name: GetSavingsSource :one
SELECT id, budget_profile_id, budget_person_id, name, amount, frequency, created_at, is_tax_reserve, federal_amount, state_amount, payment_method_id, payment_days
FROM savings_source
WHERE id = $1 AND budget_profile_id = $2
LIMIT 1
`

type GetSavingsSourceParams struct {
	ID              int32     `json:"id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

func (q *Queries) GetSavingsSource(ctx context.Context, arg GetSavingsSourceParams) (SavingsSource, error) {
	row := q.db.QueryRow(ctx, getSavingsSource, arg.ID, arg.BudgetProfileID)
	var i SavingsSource
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.BudgetPersonID,
		&i.Name,
		&i.Amount,
		&i.Frequency,
		&i.CreatedAt,
		&i.IsTaxReserve,
		&i.FederalAmount,
		&i.StateAmount,
		&i.PaymentMethodID,
		&i.PaymentDays,
	)
	return i, err
}

const linkBudgetPersonToUser = `-- name: LinkBudgetPersonToUser :one
UPDATE budget_to_profile_mapping
SET user_id = $1::uuid, role = $2
WHERE id = $3 AND is_active = TRUE
RETURNING id, budget_profile_id, user_name, user_id, is_active, color, role
`

type LinkBudgetPersonToUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
	ID     int32     `json:"id"`
}

func (q *Queries) LinkBudgetPersonToUser(ctx context.Context, arg LinkBudgetPersonToUserParams) (BudgetToProfileMapping, error) {
	row := q.db.QueryRow(ctx, linkBudgetPersonToUser, arg.UserID, arg.Role, arg.ID)
	var i BudgetToProfileMapping
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.UserName,
		&i.UserID,
		&i.IsActive,
		&i.Color,
		&i.Role,
	)
	return i, err
}

const listBudgetPeopleByProfile = `-- name: ListBudgetPeopleByProfile :many
SELECT id, budget_profile_id, user_name, user_id, is_active, color, role
FROM budget_to_profile_mapping
WHERE budget_profile_id = $1 AND is_active = TRUE
ORDER BY id
`

func (q *Queries) ListBudgetPeopleByProfile(ctx context.Context, budgetProfileID uuid.UUID) ([]BudgetToProfileMapping, error) {
	rows, err := q.db.Query(ctx, listBudgetPeopleByProfile, budgetProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetToProfileMapping
	for rows.Next() {
		var i BudgetToProfileMapping
		if err := rows.Scan(
			&i.ID,
			&i.BudgetProfileID,
			&i.UserName,
			&i.UserID,
			&i.IsActive,
			&i.Color,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetPeriods = `-- name: ListBudgetPeriods :many
SELECT id, budget_profile_id, start_date, end_date, is_archived, created_at
FROM budget_period
WHERE budget_profile_id = $1
ORDER BY start_date DESC
`

func (q *Queries) ListBudgetPeriods(ctx context.Context, budgetProfileID uuid.UUID) ([]BudgetPeriod, error) {
	rows, err := q.db.Query(ctx, listBudgetPeriods, budgetProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetPeriod
	for rows.Next() {
		var i BudgetPeriod
		if err := rows.Scan(
			&i.ID,
			&i.BudgetProfileID,
			&i.StartDate,
			&i.EndDate,
			&i.IsArchived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetProfilesByUser = `-- name: ListBudgetProfilesByUser :many
SELECT id, user_id, name, cycle, created_at, country_code
FROM budget_profile
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBudgetProfilesByUser(ctx context.Context, userID uuid.UUID) ([]BudgetProfile, error) {
	rows, err := q.db.Query(ctx, listBudgetProfilesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetProfile
	for rows.Next() {
		var i BudgetProfile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Cycle,
			&i.CreatedAt,
			&i.CountryCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetProfilesByUserOrMember = `-- name: ListBudgetProfilesByUserOrMember :many
SELECT DISTINCT bp.id, bp.user_id, bp.name, bp.cycle, bp.created_at, bp.country_code
FROM budget_profile bp
LEFT JOIN budget_to_profile_mapping btpm
    ON btpm.budget_profile_id = bp.id
    AND btpm.user_id = $1
    AND btpm.is_active = TRUE
WHERE bp.user_id = $1 OR btpm.id IS NOT NULL
ORDER BY bp.created_at DESC
`

func (q *Queries) ListBudgetProfilesByUserOrMember(ctx context.Context, userID *uuid.UUID) ([]BudgetProfile, error) {
	rows, err := q.db.Query(ctx, listBudgetProfilesByUserOrMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetProfile
	for rows.Next() {
		var i BudgetProfile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Cycle,
			&i.CreatedAt,
			&i.CountryCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeEntries = `-- name: ListIncomeEntries :many
SELECT id, budget_period_id, income_source_id, budget_person_id, name, amount, created_at
FROM income_entry
WHERE budget_period_id = $1
ORDER BY id
`

func (q *Queries) ListIncomeEntries(ctx context.Context, budgetPeriodID uuid.UUID) ([]IncomeEntry, error) {
	rows, err := q.db.Query(ctx, listIncomeEntries, budgetPeriodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncomeEntry
	for rows.Next() {
		var i IncomeEntry
		if err := rows.Scan(
			&i.ID,
			&i.BudgetPeriodID,
			&i.IncomeSourceID,
			&i.BudgetPersonID,
			&i.Name,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeSources = `-- name: ListIncomeSources :many
SELECT id, budget_profile_id, budget_person_id, name, income_type, default_amount, recurring, created_at, payment_frequency, before_tax
FROM income_source
WHERE budget_profile_id = $1
ORDER BY id
`

func (q *Queries) ListIncomeSources(ctx context.Context, budgetProfileID uuid.UUID) ([]IncomeSource, error) {
	rows, err := q.db.Query(ctx, listIncomeSources, budgetProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncomeSource
	for rows.Next() {
		var i IncomeSource
		if err := rows.Scan(
			&i.ID,
			&i.BudgetProfileID,
			&i.BudgetPersonID,
			&i.Name,
			&i.IncomeType,
			&i.DefaultAmount,
			&i.Recurring,
			&i.CreatedAt,
			&i.PaymentFrequency,
			&i.BeforeTax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileIDsWithLatestPeriodEndingOn = `-- name: ListProfileIDsWithLatestPeriodEndingOn :many
SELECT budget_profile_id
FROM budget_period bp
WHERE bp.end_date = $1::date
  AND NOT EXISTS (
    SELECT 1 FROM budget_period bp2
    WHERE bp2.budget_profile_id = bp.budget_profile_id
      AND bp2.start_date > bp.start_date
  )
`

// Used by the cycling job to find profiles whose current period just ended.
func (q *Queries) ListProfileIDsWithLatestPeriodEndingOn(ctx context.Context, dollar_1 pgtype.Date) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listProfileIDsWithLatestPeriodEndingOn, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var budget_profile_id uuid.UUID
		if err := rows.Scan(&budget_profile_id); err != nil {
			return nil, err
		}
		items = append(items, budget_profile_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavingsSources = `-- name: ListSavingsSources :many
SELECT id, budget_profile_id, budget_person_id, name, amount, frequency, created_at, is_tax_reserve, federal_amount, state_amount, payment_method_id, payment_days
FROM savings_source
WHERE budget_profile_id = $1
ORDER BY id
`

func (q *Queries) ListSavingsSources(ctx context.Context, budgetProfileID uuid.UUID) ([]SavingsSource, error) {
	rows, err := q.db.Query(ctx, listSavingsSources, budgetProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavingsSource
	for rows.Next() {
		var i SavingsSource
		if err := rows.Scan(
			&i.ID,
			&i.BudgetProfileID,
			&i.BudgetPersonID,
			&i.Name,
			&i.Amount,
			&i.Frequency,
			&i.CreatedAt,
			&i.IsTaxReserve,
			&i.FederalAmount,
			&i.StateAmount,
			&i.PaymentMethodID,
			&i.PaymentDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softRemovePersonAndReassignFromProfile = `-- name: SoftRemovePersonAndReassignFromProfile :exec
WITH reassign_transactions AS (
    UPDATE transaction
    SET payment_method_id = $3::uuid
    WHERE payment_method_id IN (
        SELECT pm.id FROM payment_methods pm WHERE pm.budget_person_id = $1
    )
      AND budget_period_id IN (
        SELECT bp.id FROM budget_period bp WHERE bp.budget_profile_id = $2::uuid
      )
),
soft_delete_pms AS (
    UPDATE payment_methods
    SET is_active = FALSE
    WHERE budget_person_id = $1
),
reassign_income AS (
    UPDATE income_entry
    SET budget_person_id = $4
    WHERE budget_person_id = $1
      AND budget_period_id IN (
        SELECT bp.id FROM budget_period bp WHERE bp.budget_profile_id = $2::uuid
      )
)
UPDATE budget_to_profile_mapping
SET is_active = FALSE
WHERE budget_to_profile_mapping.id = $1
  AND budget_to_profile_mapping.budget_profile_id = $2::uuid
`

type SoftRemovePersonAndReassignFromProfileParams struct {
	PersonID            int32     `json:"person_id"`
	BudgetProfileID     uuid.UUID `json:"budget_profile_id"`
	ReplacementPmID     uuid.UUID `json:"replacement_pm_id"`
	ReplacementPersonID *int32    `json:"replacement_person_id"`
}

func (q *Queries) SoftRemovePersonAndReassignFromProfile(ctx context.Context, arg SoftRemovePersonAndReassignFromProfileParams) error {
	_, err := q.db.Exec(ctx, softRemovePersonAndReassignFromProfile,
		arg.PersonID,
		arg.BudgetProfileID,
		arg.ReplacementPmID,
		arg.ReplacementPersonID,
	)
	return err
}

const softRemovePersonFromProfile = `-- name: SoftRemovePersonFromProfile :exec
WITH soft_delete_pms AS (
    UPDATE payment_methods
    SET is_active = FALSE
    WHERE budget_person_id = $1
)
UPDATE budget_to_profile_mapping
SET is_active = FALSE
WHERE budget_to_profile_mapping.id = $1
  AND budget_to_profile_mapping.budget_profile_id = $2::uuid
`

type SoftRemovePersonFromProfileParams struct {
	PersonID        int32     `json:"person_id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

func (q *Queries) SoftRemovePersonFromProfile(ctx context.Context, arg SoftRemovePersonFromProfileParams) error {
	_, err := q.db.Exec(ctx, softRemovePersonFromProfile, arg.PersonID, arg.BudgetProfileID)
	return err
}

const updateBudgetPerson = `-- name: UpdateBudgetPerson :one
UPDATE budget_to_profile_mapping
SET color = $1
WHERE id = $2 AND budget_profile_id = $3::uuid AND is_active = TRUE
RETURNING id, budget_profile_id, user_name, user_id, is_active, color, role
`

type UpdateBudgetPersonParams struct {
	Color           string    `json:"color"`
	ID              int32     `json:"id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

func (q *Queries) UpdateBudgetPerson(ctx context.Context, arg UpdateBudgetPersonParams) (BudgetToProfileMapping, error) {
	row := q.db.QueryRow(ctx, updateBudgetPerson, arg.Color, arg.ID, arg.BudgetProfileID)
	var i BudgetToProfileMapping
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.UserName,
		&i.UserID,
		&i.IsActive,
		&i.Color,
		&i.Role,
	)
	return i, err
}

const updateBudgetPersonRole = `-- name: UpdateBudgetPersonRole :one
UPDATE budget_to_profile_mapping
SET role = $1
WHERE id = $2 AND budget_profile_id = $3::uuid AND is_active = TRUE
RETURNING id, budget_profile_id, user_name, user_id, is_active, color, role
`

type UpdateBudgetPersonRoleParams struct {
	Role            string    `json:"role"`
	ID              int32     `json:"id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

func (q *Queries) UpdateBudgetPersonRole(ctx context.Context, arg UpdateBudgetPersonRoleParams) (BudgetToProfileMapping, error) {
	row := q.db.QueryRow(ctx, updateBudgetPersonRole, arg.Role, arg.ID, arg.BudgetProfileID)
	var i BudgetToProfileMapping
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.UserName,
		&i.UserID,
		&i.IsActive,
		&i.Color,
		&i.Role,
	)
	return i, err
}

const updateBudgetProfile = `-- name: UpdateBudgetProfile :one
UPDATE budget_profile
SET name = $2, cycle = $3
WHERE id = $1
RETURNING id, user_id, name, cycle, created_at, country_code
`

type UpdateBudgetProfileParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Cycle string    `json:"cycle"`
}

func (q *Queries) UpdateBudgetProfile(ctx context.Context, arg UpdateBudgetProfileParams) (BudgetProfile, error) {
	row := q.db.QueryRow(ctx, updateBudgetProfile, arg.ID, arg.Name, arg.Cycle)
	var i BudgetProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Cycle,
		&i.CreatedAt,
		&i.CountryCode,
	)
	return i, err
}

const updateIncomeEntry = `-- name: UpdateIncomeEntry :one
UPDATE income_entry
SET amount = $3
WHERE id = $1 AND budget_period_id = $2
RETURNING id, budget_period_id, income_source_id, budget_person_id, name, amount, created_at
`

type UpdateIncomeEntryParams struct {
	ID             int32          `json:"id"`
	BudgetPeriodID uuid.UUID      `json:"budget_period_id"`
	Amount         pgtype.Numeric `json:"amount"`
}

func (q *Queries) UpdateIncomeEntry(ctx context.Context, arg UpdateIncomeEntryParams) (IncomeEntry, error) {
	row := q.db.QueryRow(ctx, updateIncomeEntry, arg.ID, arg.BudgetPeriodID, arg.Amount)
	var i IncomeEntry
	err := row.Scan(
		&i.ID,
		&i.BudgetPeriodID,
		&i.IncomeSourceID,
		&i.BudgetPersonID,
		&i.Name,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const updateIncomeSource = `-- name: UpdateIncomeSource :one
UPDATE income_source
SET name = $3, income_type = $4, default_amount = $5, recurring = $6, budget_person_id = $7, payment_frequency = $8, before_tax = $9
WHERE id = $1 AND budget_profile_id = $2
RETURNING id, budget_profile_id, budget_person_id, name, income_type, default_amount, recurring, created_at, payment_frequency, before_tax
`

type UpdateIncomeSourceParams struct {
	ID               int32          `json:"id"`
	BudgetProfileID  uuid.UUID      `json:"budget_profile_id"`
	Name             string         `json:"name"`
	IncomeType       string         `json:"income_type"`
	DefaultAmount    pgtype.Numeric `json:"default_amount"`
	Recurring        bool           `json:"recurring"`
	BudgetPersonID   *int32         `json:"budget_person_id"`
	PaymentFrequency string         `json:"payment_frequency"`
	BeforeTax        bool           `json:"before_tax"`
}

func (q *Queries) UpdateIncomeSource(ctx context.Context, arg UpdateIncomeSourceParams) (IncomeSource, error) {
	row := q.db.QueryRow(ctx, updateIncomeSource,
		arg.ID,
		arg.BudgetProfileID,
		arg.Name,
		arg.IncomeType,
		arg.DefaultAmount,
		arg.Recurring,
		arg.BudgetPersonID,
		arg.PaymentFrequency,
		arg.BeforeTax,
	)
	var i IncomeSource
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.BudgetPersonID,
		&i.Name,
		&i.IncomeType,
		&i.DefaultAmount,
		&i.Recurring,
		&i.CreatedAt,
		&i.PaymentFrequency,
		&i.BeforeTax,
	)
	return i, err
}

const updateSavingsSource = `-- name: UpdateSavingsSource :one
UPDATE savings_source
SET name = $3, amount = $4, frequency = $5, budget_person_id = $6, payment_method_id = $7, payment_days = $8
WHERE id = $1 AND budget_profile_id = $2
RETURNING id, budget_profile_id, budget_person_id, name, amount, frequency, created_at, is_tax_reserve, federal_amount, state_amount, payment_method_id, payment_days
`

type UpdateSavingsSourceParams struct {
	ID              int32          `json:"id"`
	BudgetProfileID uuid.UUID      `json:"budget_profile_id"`
	Name            string         `json:"name"`
	Amount          pgtype.Numeric `json:"amount"`
	Frequency       string         `json:"frequency"`
	BudgetPersonID  *int32         `json:"budget_person_id"`
	PaymentMethodID *uuid.UUID     `json:"payment_method_id"`
	PaymentDays     []int32        `json:"payment_days"`
}

func (q *Queries) UpdateSavingsSource(ctx context.Context, arg UpdateSavingsSourceParams) (SavingsSource, error) {
	row := q.db.QueryRow(ctx, updateSavingsSource,
		arg.ID,
		arg.BudgetProfileID,
		arg.Name,
		arg.Amount,
		arg.Frequency,
		arg.BudgetPersonID,
		arg.PaymentMethodID,
		arg.PaymentDays,
	)
	var i SavingsSource
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.BudgetPersonID,
		&i.Name,
		&i.Amount,
		&i.Frequency,
		&i.CreatedAt,
		&i.IsTaxReserve,
		&i.FederalAmount,
		&i.StateAmount,
		&i.PaymentMethodID,
		&i.PaymentDays,
	)
	return i, err
}

const upsertTaxReserveSavingsSource = `-- name: UpsertTaxReserveSavingsSource :one
INSERT INTO savings_source (budget_profile_id, budget_person_id, name, amount, frequency, is_tax_reserve, federal_amount, state_amount)
VALUES ($1::uuid, $2, 'Future Tax Payment', $3, 'monthly', TRUE, $4, $5)
ON CONFLICT (budget_profile_id, budget_person_id) WHERE is_tax_reserve = TRUE
DO UPDATE SET amount = EXCLUDED.amount, federal_amount = EXCLUDED.federal_amount, state_amount = EXCLUDED.state_amount
RETURNING id, budget_profile_id, budget_person_id, name, amount, frequency, created_at, is_tax_reserve, federal_amount, state_amount, payment_method_id, payment_days
`

type UpsertTaxReserveSavingsSourceParams struct {
	BudgetProfileID uuid.UUID      `json:"budget_profile_id"`
	BudgetPersonID  *int32         `json:"budget_person_id"`
	Amount          pgtype.Numeric `json:"amount"`
	FederalAmount   pgtype.Numeric `json:"federal_amount"`
	StateAmount     pgtype.Numeric `json:"state_amount"`
}

// Upserts the system-managed tax reserve savings source for a budget profile.
// Uses the partial unique index idx_savings_source_tax_reserve.
func (q *Queries) UpsertTaxReserveSavingsSource(ctx context.Context, arg UpsertTaxReserveSavingsSourceParams) (SavingsSource, error) {
	row := q.db.QueryRow(ctx, upsertTaxReserveSavingsSource,
		arg.BudgetProfileID,
		arg.BudgetPersonID,
		arg.Amount,
		arg.FederalAmount,
		arg.StateAmount,
	)
	var i SavingsSource
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.BudgetPersonID,
		&i.Name,
		&i.Amount,
		&i.Frequency,
		&i.CreatedAt,
		&i.IsTaxReserve,
		&i.FederalAmount,
		&i.StateAmount,
		&i.PaymentMethodID,
		&i.PaymentDays,
	)
	return i, err
}
