// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense_allocation.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpenseAllocation = `-- name: DeleteExpenseAllocation :exec
DELETE FROM expense_allocation WHERE id = $1 AND budget_profile_id = $2
`

type DeleteExpenseAllocationParams struct {
	ID              int32     `json:"id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

func (q *Queries) DeleteExpenseAllocation(ctx context.Context, arg DeleteExpenseAllocationParams) error {
	_, err := q.db.Exec(ctx, deleteExpenseAllocation, arg.ID, arg.BudgetProfileID)
	return err
}

const listExpenseAllocations = `-- name: ListExpenseAllocations :many
SELECT id, budget_profile_id, category_id, budget_person_id, planned_amount
FROM expense_allocation
WHERE budget_profile_id = $1
ORDER BY category_id, id
`

func (q *Queries) ListExpenseAllocations(ctx context.Context, budgetProfileID uuid.UUID) ([]ExpenseAllocation, error) {
	rows, err := q.db.Query(ctx, listExpenseAllocations, budgetProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseAllocation
	for rows.Next() {
		var i ExpenseAllocation
		if err := rows.Scan(
			&i.ID,
			&i.BudgetProfileID,
			&i.CategoryID,
			&i.BudgetPersonID,
			&i.PlannedAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExpenseAllocation = `-- name: UpsertExpenseAllocation :one
INSERT INTO expense_allocation (budget_profile_id, category_id, budget_person_id, planned_amount)
VALUES ($1::uuid, $2, $3, $4)
ON CONFLICT (budget_profile_id, category_id, COALESCE(budget_person_id, -1))
DO UPDATE SET planned_amount = EXCLUDED.planned_amount
RETURNING id, budget_profile_id, category_id, budget_person_id, planned_amount
`

type UpsertExpenseAllocationParams struct {
	BudgetProfileID uuid.UUID      `json:"budget_profile_id"`
	CategoryID      int32          `json:"category_id"`
	BudgetPersonID  *int32         `json:"budget_person_id"`
	PlannedAmount   pgtype.Numeric `json:"planned_amount"`
}

func (q *Queries) UpsertExpenseAllocation(ctx context.Context, arg UpsertExpenseAllocationParams) (ExpenseAllocation, error) {
	row := q.db.QueryRow(ctx, upsertExpenseAllocation,
		arg.BudgetProfileID,
		arg.CategoryID,
		arg.BudgetPersonID,
		arg.PlannedAmount,
	)
	var i ExpenseAllocation
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.CategoryID,
		&i.BudgetPersonID,
		&i.PlannedAmount,
	)
	return i, err
}
