// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fixed_expense.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFixedExpense = `-- name: CreateFixedExpense :one
INSERT INTO fixed_expense (budget_profile_id, name, planned_amount, category_id, payment_method_id, day_of_month, interval_months)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, budget_profile_id, name, planned_amount, category_id, payment_method_id, day_of_month, is_active, created_at, interval_months
`

type CreateFixedExpenseParams struct {
	BudgetProfileID uuid.UUID      `json:"budget_profile_id"`
	Name            string         `json:"name"`
	PlannedAmount   pgtype.Numeric `json:"planned_amount"`
	CategoryID      *int32         `json:"category_id"`
	PaymentMethodID *uuid.UUID     `json:"payment_method_id"`
	DayOfMonth      int32          `json:"day_of_month"`
	IntervalMonths  int32          `json:"interval_months"`
}

func (q *Queries) CreateFixedExpense(ctx context.Context, arg CreateFixedExpenseParams) (FixedExpense, error) {
	row := q.db.QueryRow(ctx, createFixedExpense,
		arg.BudgetProfileID,
		arg.Name,
		arg.PlannedAmount,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.DayOfMonth,
		arg.IntervalMonths,
	)
	var i FixedExpense
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.Name,
		&i.PlannedAmount,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.DayOfMonth,
		&i.IsActive,
		&i.CreatedAt,
		&i.IntervalMonths,
	)
	return i, err
}

const deactivateFixedExpense = `-- name: DeactivateFixedExpense :exec
UPDATE fixed_expense
SET is_active = FALSE
WHERE id = $1::uuid
  AND budget_profile_id = $2::uuid
`

type DeactivateFixedExpenseParams struct {
	ID              uuid.UUID `json:"id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

func (q *Queries) DeactivateFixedExpense(ctx context.Context, arg DeactivateFixedExpenseParams) error {
	_, err := q.db.Exec(ctx, deactivateFixedExpense, arg.ID, arg.BudgetProfileID)
	return err
}

const deleteUnpaidTransactionByFixedExpense = `-- name: DeleteUnpaidTransactionByFixedExpense :exec
DELETE FROM transaction
WHERE fixed_expense_id = $1::uuid
  AND is_paid = FALSE
  AND budget_period_id IN (
      SELECT id FROM budget_period
      WHERE budget_profile_id = $2::uuid
        AND is_archived = FALSE
  )
`

type DeleteUnpaidTransactionByFixedExpenseParams struct {
	FixedExpenseID  uuid.UUID `json:"fixed_expense_id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

func (q *Queries) DeleteUnpaidTransactionByFixedExpense(ctx context.Context, arg DeleteUnpaidTransactionByFixedExpenseParams) error {
	_, err := q.db.Exec(ctx, deleteUnpaidTransactionByFixedExpense, arg.FixedExpenseID, arg.BudgetProfileID)
	return err
}

const fixedExpenseHasTransactionInMonth = `-- name: FixedExpenseHasTransactionInMonth :one
SELECT EXISTS (
    SELECT 1 FROM transaction
    WHERE fixed_expense_id = $1::uuid
      AND date >= $2::date
      AND date < $3::date
) AS exists
`

type FixedExpenseHasTransactionInMonthParams struct {
	FixedExpenseID uuid.UUID   `json:"fixed_expense_id"`
	MonthStart     pgtype.Date `json:"month_start"`
	MonthEnd       pgtype.Date `json:"month_end"`
}

func (q *Queries) FixedExpenseHasTransactionInMonth(ctx context.Context, arg FixedExpenseHasTransactionInMonthParams) (bool, error) {
	row := q.db.QueryRow(ctx, fixedExpenseHasTransactionInMonth, arg.FixedExpenseID, arg.MonthStart, arg.MonthEnd)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFixedExpense = `-- name: GetFixedExpense :one
SELECT id, budget_profile_id, name, planned_amount, category_id, payment_method_id, day_of_month, is_active, created_at, interval_months
FROM fixed_expense
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFixedExpense(ctx context.Context, id uuid.UUID) (FixedExpense, error) {
	row := q.db.QueryRow(ctx, getFixedExpense, id)
	var i FixedExpense
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.Name,
		&i.PlannedAmount,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.DayOfMonth,
		&i.IsActive,
		&i.CreatedAt,
		&i.IntervalMonths,
	)
	return i, err
}

const getUnpaidTransactionByFixedExpense = `-- name: GetUnpaidTransactionByFixedExpense :one
SELECT id, name, amount, planned_amount, date, renewal_date, recurring,
       budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
       is_paid, paid_date, fixed_expense_id
FROM transaction
WHERE fixed_expense_id = $1::uuid
  AND is_paid = FALSE
  AND budget_period_id IN (
      SELECT id FROM budget_period
      WHERE budget_profile_id = $2::uuid
        AND is_archived = FALSE
  )
ORDER BY date DESC NULLS LAST
LIMIT 1
`

type GetUnpaidTransactionByFixedExpenseParams struct {
	FixedExpenseID  uuid.UUID `json:"fixed_expense_id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

func (q *Queries) GetUnpaidTransactionByFixedExpense(ctx context.Context, arg GetUnpaidTransactionByFixedExpenseParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getUnpaidTransactionByFixedExpense, arg.FixedExpenseID, arg.BudgetProfileID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.Recurring,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
	)
	return i, err
}

const listFixedExpenses = `-- name: ListFixedExpenses :many
SELECT id, budget_profile_id, name, planned_amount, category_id, payment_method_id, day_of_month, is_active, created_at, interval_months
FROM fixed_expense
WHERE budget_profile_id = $1 AND is_active = TRUE
ORDER BY name
`

func (q *Queries) ListFixedExpenses(ctx context.Context, budgetProfileID uuid.UUID) ([]FixedExpense, error) {
	rows, err := q.db.Query(ctx, listFixedExpenses, budgetProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FixedExpense
	for rows.Next() {
		var i FixedExpense
		if err := rows.Scan(
			&i.ID,
			&i.BudgetProfileID,
			&i.Name,
			&i.PlannedAmount,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.DayOfMonth,
			&i.IsActive,
			&i.CreatedAt,
			&i.IntervalMonths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFixedExpense = `-- name: UpdateFixedExpense :one
UPDATE fixed_expense
SET name              = $1,
    planned_amount    = $2,
    category_id       = $3,
    payment_method_id = $4,
    day_of_month      = $5,
    interval_months   = $6
WHERE id = $7::uuid
  AND budget_profile_id = $8::uuid
RETURNING id, budget_profile_id, name, planned_amount, category_id, payment_method_id, day_of_month, is_active, created_at, interval_months
`

type UpdateFixedExpenseParams struct {
	Name            string         `json:"name"`
	PlannedAmount   pgtype.Numeric `json:"planned_amount"`
	CategoryID      *int32         `json:"category_id"`
	PaymentMethodID *uuid.UUID     `json:"payment_method_id"`
	DayOfMonth      int32          `json:"day_of_month"`
	IntervalMonths  int32          `json:"interval_months"`
	ID              uuid.UUID      `json:"id"`
	BudgetProfileID uuid.UUID      `json:"budget_profile_id"`
}

func (q *Queries) UpdateFixedExpense(ctx context.Context, arg UpdateFixedExpenseParams) (FixedExpense, error) {
	row := q.db.QueryRow(ctx, updateFixedExpense,
		arg.Name,
		arg.PlannedAmount,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.DayOfMonth,
		arg.IntervalMonths,
		arg.ID,
		arg.BudgetProfileID,
	)
	var i FixedExpense
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.Name,
		&i.PlannedAmount,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.DayOfMonth,
		&i.IsActive,
		&i.CreatedAt,
		&i.IntervalMonths,
	)
	return i, err
}

const updateFixedExpensePlannedAmount = `-- name: UpdateFixedExpensePlannedAmount :exec
UPDATE fixed_expense
SET planned_amount = $1
WHERE id = $2::uuid
`

type UpdateFixedExpensePlannedAmountParams struct {
	PlannedAmount pgtype.Numeric `json:"planned_amount"`
	ID            uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateFixedExpensePlannedAmount(ctx context.Context, arg UpdateFixedExpensePlannedAmountParams) error {
	_, err := q.db.Exec(ctx, updateFixedExpensePlannedAmount, arg.PlannedAmount, arg.ID)
	return err
}

const updateTransactionFromFixedExpense = `-- name: UpdateTransactionFromFixedExpense :exec
UPDATE transaction
SET name              = $1,
    planned_amount    = $2,
    amount            = $2,
    category_id       = $3,
    payment_method_id = $4,
    date              = $5
WHERE fixed_expense_id = $6::uuid
  AND is_paid = FALSE
  AND budget_period_id IN (
      SELECT id FROM budget_period
      WHERE budget_profile_id = $7::uuid
        AND is_archived = FALSE
  )
`

type UpdateTransactionFromFixedExpenseParams struct {
	Name            *string        `json:"name"`
	PlannedAmount   pgtype.Numeric `json:"planned_amount"`
	CategoryID      *int32         `json:"category_id"`
	PaymentMethodID *uuid.UUID     `json:"payment_method_id"`
	Date            pgtype.Date    `json:"date"`
	FixedExpenseID  uuid.UUID      `json:"fixed_expense_id"`
	BudgetProfileID uuid.UUID      `json:"budget_profile_id"`
}

func (q *Queries) UpdateTransactionFromFixedExpense(ctx context.Context, arg UpdateTransactionFromFixedExpenseParams) error {
	_, err := q.db.Exec(ctx, updateTransactionFromFixedExpense,
		arg.Name,
		arg.PlannedAmount,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.Date,
		arg.FixedExpenseID,
		arg.BudgetProfileID,
	)
	return err
}
