// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO budget_invite (budget_profile_id, email, role, invited_by, budget_person_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, budget_profile_id, email, role, token, status, invited_by, budget_person_id, expires_at, created_at
`

type CreateInviteParams struct {
	BudgetProfileID uuid.UUID          `json:"budget_profile_id"`
	Email           string             `json:"email"`
	Role            string             `json:"role"`
	InvitedBy       uuid.UUID          `json:"invited_by"`
	BudgetPersonID  *int64             `json:"budget_person_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (BudgetInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.BudgetProfileID,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
		arg.BudgetPersonID,
		arg.ExpiresAt,
	)
	var i BudgetInvite
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.BudgetPersonID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByID = `-- name: GetInviteByID :one
SELECT id, budget_profile_id, email, role, token, status, invited_by, budget_person_id, expires_at, created_at
FROM budget_invite
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetInviteByID(ctx context.Context, id uuid.UUID) (BudgetInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByID, id)
	var i BudgetInvite
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.BudgetPersonID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT
    bi.id, bi.budget_profile_id, bi.email, bi.role, bi.token, bi.status,
    bi.invited_by, bi.budget_person_id, bi.expires_at, bi.created_at,
    bp.name  AS budget_name,
    COALESCE(u.first_name || ' ' || u.last_name, u.email) AS inviter_name
FROM budget_invite bi
JOIN budget_profile bp ON bp.id = bi.budget_profile_id
JOIN users u ON u.id = bi.invited_by
WHERE bi.token = $1
LIMIT 1
`

type GetInviteByTokenRow struct {
	ID              uuid.UUID          `json:"id"`
	BudgetProfileID uuid.UUID          `json:"budget_profile_id"`
	Email           string             `json:"email"`
	Role            string             `json:"role"`
	Token           uuid.UUID          `json:"token"`
	Status          string             `json:"status"`
	InvitedBy       uuid.UUID          `json:"invited_by"`
	BudgetPersonID  *int64             `json:"budget_person_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	BudgetName      string             `json:"budget_name"`
	InviterName     string             `json:"inviter_name"`
}

func (q *Queries) GetInviteByToken(ctx context.Context, token uuid.UUID) (GetInviteByTokenRow, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, token)
	var i GetInviteByTokenRow
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.BudgetPersonID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.BudgetName,
		&i.InviterName,
	)
	return i, err
}

const listInvitesByProfile = `-- name: ListInvitesByProfile :many
SELECT id, budget_profile_id, email, role, token, status, invited_by, budget_person_id, expires_at, created_at
FROM budget_invite
WHERE budget_profile_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListInvitesByProfile(ctx context.Context, budgetProfileID uuid.UUID) ([]BudgetInvite, error) {
	rows, err := q.db.Query(ctx, listInvitesByProfile, budgetProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetInvite
	for rows.Next() {
		var i BudgetInvite
		if err := rows.Scan(
			&i.ID,
			&i.BudgetProfileID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.Status,
			&i.InvitedBy,
			&i.BudgetPersonID,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInviteStatus = `-- name: UpdateInviteStatus :one
UPDATE budget_invite
SET status = $2
WHERE id = $1
RETURNING id, budget_profile_id, email, role, token, status, invited_by, budget_person_id, expires_at, created_at
`

type UpdateInviteStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateInviteStatus(ctx context.Context, arg UpdateInviteStatusParams) (BudgetInvite, error) {
	row := q.db.QueryRow(ctx, updateInviteStatus, arg.ID, arg.Status)
	var i BudgetInvite
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.BudgetPersonID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
