// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Budget struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	Name      string      `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Active    bool        `json:"active"`
}

type BudgetToUserMapping struct {
	ID       int32      `json:"id"`
	BudgetID uuid.UUID  `json:"budget_id"`
	UserName *string    `json:"user_name"`
	UserID   *uuid.UUID `json:"user_id"`
}

type Category struct {
	ID       int32      `json:"id"`
	Name     string     `json:"name"`
	TypeID   *int32     `json:"type_id"`
	UserID   *uuid.UUID `json:"user_id"`
	IsSystem bool       `json:"is_system"`
	IsActive bool       `json:"is_active"`
}

type CategoryType struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type IncomeToBudgetMapping struct {
	ID             int32          `json:"id"`
	BudgetID       uuid.UUID      `json:"budget_id"`
	UserID         *uuid.UUID     `json:"user_id"`
	Name           *string        `json:"name"`
	Amount         pgtype.Numeric `json:"amount"`
	Recurring      bool           `json:"recurring"`
	BudgetPersonID *int32         `json:"budget_person_id"`
}

type OauthAccount struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	OauthName    string    `json:"oauth_name"`
	AccountID    string    `json:"account_id"`
	AccountEmail string    `json:"account_email"`
}

type PaymentMethod struct {
	ID             uuid.UUID  `json:"id"`
	Name           string     `json:"name"`
	PaymentTypeID  *int32     `json:"payment_type_id"`
	UserID         *uuid.UUID `json:"user_id"`
	IsActive       bool       `json:"is_active"`
	BudgetPersonID *int32     `json:"budget_person_id"`
}

type PaymentType struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Transaction struct {
	ID                     uuid.UUID      `json:"id"`
	Name                   *string        `json:"name"`
	Amount                 pgtype.Numeric `json:"amount"`
	PlannedAmount          pgtype.Numeric `json:"planned_amount"`
	Date                   pgtype.Date    `json:"date"`
	RenewalDate            pgtype.Date    `json:"renewal_date"`
	Recurring              *bool          `json:"recurring"`
	BudgetID               *uuid.UUID     `json:"budget_id"`
	CategoryID             *int32         `json:"category_id"`
	PaymentMethodID        *uuid.UUID     `json:"payment_method_id"`
	TransactionFrequencyID *int32         `json:"transaction_frequency_id"`
	TransactionTypeID      *int32         `json:"transaction_type_id"`
}

type TransactionFrequency struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type TransactionType struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Email          string             `json:"email"`
	HashedPassword *string            `json:"hashed_password"`
	FirstName      *string            `json:"first_name"`
	LastName       *string            `json:"last_name"`
	IsActive       bool               `json:"is_active"`
	IsSuperuser    bool               `json:"is_superuser"`
	IsVerified     bool               `json:"is_verified"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
