// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BudgetInvite struct {
	ID              uuid.UUID          `json:"id"`
	BudgetProfileID uuid.UUID          `json:"budget_profile_id"`
	Email           string             `json:"email"`
	Role            string             `json:"role"`
	Token           uuid.UUID          `json:"token"`
	Status          string             `json:"status"`
	InvitedBy       uuid.UUID          `json:"invited_by"`
	BudgetPersonID  *int64             `json:"budget_person_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type BudgetPeriod struct {
	ID              uuid.UUID          `json:"id"`
	BudgetProfileID uuid.UUID          `json:"budget_profile_id"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	IsArchived      bool               `json:"is_archived"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type BudgetProfile struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Name        string             `json:"name"`
	Cycle       string             `json:"cycle"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CountryCode *string            `json:"country_code"`
}

type BudgetToProfileMapping struct {
	ID              int32      `json:"id"`
	BudgetProfileID uuid.UUID  `json:"budget_profile_id"`
	UserName        *string    `json:"user_name"`
	UserID          *uuid.UUID `json:"user_id"`
	IsActive        bool       `json:"is_active"`
	Color           string     `json:"color"`
	Role            string     `json:"role"`
}

type Category struct {
	ID       int32      `json:"id"`
	Name     string     `json:"name"`
	TypeID   *int32     `json:"type_id"`
	UserID   *uuid.UUID `json:"user_id"`
	IsSystem bool       `json:"is_system"`
	IsActive bool       `json:"is_active"`
	Color    string     `json:"color"`
}

type CategoryType struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Country struct {
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	IsEnabled bool               `json:"is_enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CountryFeature struct {
	CountryCode string `json:"country_code"`
	FeatureName string `json:"feature_name"`
	IsEnabled   bool   `json:"is_enabled"`
}

type ExpenseAllocation struct {
	ID              int32          `json:"id"`
	BudgetProfileID uuid.UUID      `json:"budget_profile_id"`
	CategoryID      int32          `json:"category_id"`
	BudgetPersonID  *int32         `json:"budget_person_id"`
	PlannedAmount   pgtype.Numeric `json:"planned_amount"`
}

type FixedExpense struct {
	ID              uuid.UUID          `json:"id"`
	BudgetProfileID uuid.UUID          `json:"budget_profile_id"`
	Name            string             `json:"name"`
	PlannedAmount   pgtype.Numeric     `json:"planned_amount"`
	CategoryID      *int32             `json:"category_id"`
	PaymentMethodID *uuid.UUID         `json:"payment_method_id"`
	DayOfMonth      int32              `json:"day_of_month"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	IntervalMonths  int32              `json:"interval_months"`
}

type IncomeEntry struct {
	ID             int32              `json:"id"`
	BudgetPeriodID uuid.UUID          `json:"budget_period_id"`
	IncomeSourceID *int32             `json:"income_source_id"`
	BudgetPersonID *int32             `json:"budget_person_id"`
	Name           *string            `json:"name"`
	Amount         pgtype.Numeric     `json:"amount"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type IncomeSource struct {
	ID               int32              `json:"id"`
	BudgetProfileID  uuid.UUID          `json:"budget_profile_id"`
	BudgetPersonID   *int32             `json:"budget_person_id"`
	Name             string             `json:"name"`
	IncomeType       string             `json:"income_type"`
	DefaultAmount    pgtype.Numeric     `json:"default_amount"`
	Recurring        bool               `json:"recurring"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	PaymentFrequency string             `json:"payment_frequency"`
	BeforeTax        bool               `json:"before_tax"`
}

type OauthAccount struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	OauthName    string    `json:"oauth_name"`
	AccountID    string    `json:"account_id"`
	AccountEmail string    `json:"account_email"`
}

type PaymentMethod struct {
	ID             uuid.UUID  `json:"id"`
	Name           string     `json:"name"`
	PaymentTypeID  *int32     `json:"payment_type_id"`
	UserID         *uuid.UUID `json:"user_id"`
	IsActive       bool       `json:"is_active"`
	BudgetPersonID *int32     `json:"budget_person_id"`
	Color          string     `json:"color"`
}

type PaymentType struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type SavingsSource struct {
	ID              int32              `json:"id"`
	BudgetProfileID uuid.UUID          `json:"budget_profile_id"`
	BudgetPersonID  *int32             `json:"budget_person_id"`
	Name            string             `json:"name"`
	Amount          pgtype.Numeric     `json:"amount"`
	Frequency       string             `json:"frequency"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	IsTaxReserve    bool               `json:"is_tax_reserve"`
	FederalAmount   pgtype.Numeric     `json:"federal_amount"`
	StateAmount     pgtype.Numeric     `json:"state_amount"`
	PaymentMethodID *uuid.UUID         `json:"payment_method_id"`
	PaymentDays     []int32            `json:"payment_days"`
}

type Transaction struct {
	ID                     uuid.UUID      `json:"id"`
	Name                   *string        `json:"name"`
	Amount                 pgtype.Numeric `json:"amount"`
	PlannedAmount          pgtype.Numeric `json:"planned_amount"`
	Date                   pgtype.Date    `json:"date"`
	RenewalDate            pgtype.Date    `json:"renewal_date"`
	Recurring              *bool          `json:"recurring"`
	BudgetPeriodID         *uuid.UUID     `json:"budget_period_id"`
	CategoryID             *int32         `json:"category_id"`
	PaymentMethodID        *uuid.UUID     `json:"payment_method_id"`
	TransactionFrequencyID *int32         `json:"transaction_frequency_id"`
	TransactionTypeID      *int32         `json:"transaction_type_id"`
	IsPaid                 bool           `json:"is_paid"`
	PaidDate               pgtype.Date    `json:"paid_date"`
	FixedExpenseID         *uuid.UUID     `json:"fixed_expense_id"`
}

type TransactionFrequency struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type TransactionType struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID                  uuid.UUID          `json:"id"`
	Email               string             `json:"email"`
	HashedPassword      *string            `json:"hashed_password"`
	FirstName           *string            `json:"first_name"`
	LastName            *string            `json:"last_name"`
	IsActive            bool               `json:"is_active"`
	IsSuperuser         bool               `json:"is_superuser"`
	IsVerified          bool               `json:"is_verified"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	CountryCode         *string            `json:"country_code"`
	StateCode           *string            `json:"state_code"`
	FilingStatus        string             `json:"filing_status"`
	TaxPaymentFrequency int32              `json:"tax_payment_frequency"`
	Language            string             `json:"language"`
	Currency            string             `json:"currency"`
}
