// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plaid.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPlaidItem = `-- name: CreatePlaidItem :one
INSERT INTO plaid_item (user_id, budget_profile_id, access_token, item_id, institution_id, institution_name)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, budget_profile_id, access_token, item_id, institution_id, institution_name,
          status, cursor, last_synced_at, created_at
`

type CreatePlaidItemParams struct {
	UserID          uuid.UUID `json:"user_id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
	AccessToken     string    `json:"access_token"`
	ItemID          string    `json:"item_id"`
	InstitutionID   *string   `json:"institution_id"`
	InstitutionName *string   `json:"institution_name"`
}

func (q *Queries) CreatePlaidItem(ctx context.Context, arg CreatePlaidItemParams) (PlaidItem, error) {
	row := q.db.QueryRow(ctx, createPlaidItem,
		arg.UserID,
		arg.BudgetProfileID,
		arg.AccessToken,
		arg.ItemID,
		arg.InstitutionID,
		arg.InstitutionName,
	)
	var i PlaidItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetProfileID,
		&i.AccessToken,
		&i.ItemID,
		&i.InstitutionID,
		&i.InstitutionName,
		&i.Status,
		&i.Cursor,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePlaidItem = `-- name: DeletePlaidItem :exec
DELETE FROM plaid_item WHERE id = $1
`

func (q *Queries) DeletePlaidItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlaidItem, id)
	return err
}

const getPlaidItemByID = `-- name: GetPlaidItemByID :one
SELECT id, user_id, budget_profile_id, access_token, item_id, institution_id, institution_name,
       status, cursor, last_synced_at, created_at
FROM plaid_item
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPlaidItemByID(ctx context.Context, id uuid.UUID) (PlaidItem, error) {
	row := q.db.QueryRow(ctx, getPlaidItemByID, id)
	var i PlaidItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetProfileID,
		&i.AccessToken,
		&i.ItemID,
		&i.InstitutionID,
		&i.InstitutionName,
		&i.Status,
		&i.Cursor,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPlaidItemByItemID = `-- name: GetPlaidItemByItemID :one
SELECT id, user_id, budget_profile_id, access_token, item_id, institution_id, institution_name,
       status, cursor, last_synced_at, created_at
FROM plaid_item
WHERE item_id = $1
LIMIT 1
`

func (q *Queries) GetPlaidItemByItemID(ctx context.Context, itemID string) (PlaidItem, error) {
	row := q.db.QueryRow(ctx, getPlaidItemByItemID, itemID)
	var i PlaidItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetProfileID,
		&i.AccessToken,
		&i.ItemID,
		&i.InstitutionID,
		&i.InstitutionName,
		&i.Status,
		&i.Cursor,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActivePlaidItemsForSync = `-- name: ListActivePlaidItemsForSync :many
SELECT id, user_id, budget_profile_id, access_token, item_id, institution_id, institution_name,
       status, cursor, last_synced_at, created_at
FROM plaid_item
WHERE status = 'active'
  AND (last_synced_at IS NULL OR last_synced_at < NOW() - INTERVAL '3 days')
ORDER BY last_synced_at ASC NULLS FIRST
`

// Returns all active items due for a sync (never synced, or last sync older than 3 days).
func (q *Queries) ListActivePlaidItemsForSync(ctx context.Context) ([]PlaidItem, error) {
	rows, err := q.db.Query(ctx, listActivePlaidItemsForSync)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaidItem
	for rows.Next() {
		var i PlaidItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BudgetProfileID,
			&i.AccessToken,
			&i.ItemID,
			&i.InstitutionID,
			&i.InstitutionName,
			&i.Status,
			&i.Cursor,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaidItemsByBudgetProfile = `-- name: ListPlaidItemsByBudgetProfile :many
SELECT id, user_id, budget_profile_id, access_token, item_id, institution_id, institution_name,
       status, cursor, last_synced_at, created_at
FROM plaid_item
WHERE budget_profile_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPlaidItemsByBudgetProfile(ctx context.Context, budgetProfileID uuid.UUID) ([]PlaidItem, error) {
	rows, err := q.db.Query(ctx, listPlaidItemsByBudgetProfile, budgetProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaidItem
	for rows.Next() {
		var i PlaidItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BudgetProfileID,
			&i.AccessToken,
			&i.ItemID,
			&i.InstitutionID,
			&i.InstitutionName,
			&i.Status,
			&i.Cursor,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaidItemsByUser = `-- name: ListPlaidItemsByUser :many
SELECT id, user_id, budget_profile_id, access_token, item_id, institution_id, institution_name,
       status, cursor, last_synced_at, created_at
FROM plaid_item
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPlaidItemsByUser(ctx context.Context, userID uuid.UUID) ([]PlaidItem, error) {
	rows, err := q.db.Query(ctx, listPlaidItemsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaidItem
	for rows.Next() {
		var i PlaidItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BudgetProfileID,
			&i.AccessToken,
			&i.ItemID,
			&i.InstitutionID,
			&i.InstitutionName,
			&i.Status,
			&i.Cursor,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlaidItemStatus = `-- name: UpdatePlaidItemStatus :one
UPDATE plaid_item
SET status = $2
WHERE id = $1
RETURNING id, user_id, budget_profile_id, access_token, item_id, institution_id, institution_name,
          status, cursor, last_synced_at, created_at
`

type UpdatePlaidItemStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePlaidItemStatus(ctx context.Context, arg UpdatePlaidItemStatusParams) (PlaidItem, error) {
	row := q.db.QueryRow(ctx, updatePlaidItemStatus, arg.ID, arg.Status)
	var i PlaidItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetProfileID,
		&i.AccessToken,
		&i.ItemID,
		&i.InstitutionID,
		&i.InstitutionName,
		&i.Status,
		&i.Cursor,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updatePlaidItemSync = `-- name: UpdatePlaidItemSync :one
UPDATE plaid_item
SET cursor = $1, last_synced_at = NOW()
WHERE id = $2::uuid
RETURNING id, user_id, budget_profile_id, access_token, item_id, institution_id, institution_name,
          status, cursor, last_synced_at, created_at
`

type UpdatePlaidItemSyncParams struct {
	Cursor *string   `json:"cursor"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePlaidItemSync(ctx context.Context, arg UpdatePlaidItemSyncParams) (PlaidItem, error) {
	row := q.db.QueryRow(ctx, updatePlaidItemSync, arg.Cursor, arg.ID)
	var i PlaidItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetProfileID,
		&i.AccessToken,
		&i.ItemID,
		&i.InstitutionID,
		&i.InstitutionName,
		&i.Status,
		&i.Cursor,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}
