// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO category (name, type_id, user_id)
VALUES ($1, $2, $3)
RETURNING id, name, type_id, user_id
`

type CreateCategoryParams struct {
	Name   string     `json:"name"`
	TypeID *int32     `json:"type_id"`
	UserID *uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.TypeID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TypeID,
		&i.UserID,
	)
	return i, err
}

const createPaymentMethod = `-- name: CreatePaymentMethod :one
INSERT INTO payment_methods (name, payment_type_id, user_id)
VALUES ($1, $2, $3)
RETURNING id, name, payment_type_id, user_id
`

type CreatePaymentMethodParams struct {
	Name          string     `json:"name"`
	PaymentTypeID *int32     `json:"payment_type_id"`
	UserID        *uuid.UUID `json:"user_id"`
}

func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, createPaymentMethod, arg.Name, arg.PaymentTypeID, arg.UserID)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PaymentTypeID,
		&i.UserID,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transaction (
    name, amount, planned_amount, date, renewal_date, recurring,
    budget_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, amount, planned_amount, date, renewal_date, recurring,
          budget_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id
`

type CreateTransactionParams struct {
	Name                   *string        `json:"name"`
	Amount                 pgtype.Numeric `json:"amount"`
	PlannedAmount          pgtype.Numeric `json:"planned_amount"`
	Date                   pgtype.Date    `json:"date"`
	RenewalDate            pgtype.Date    `json:"renewal_date"`
	Recurring              *bool          `json:"recurring"`
	BudgetID               *uuid.UUID     `json:"budget_id"`
	CategoryID             *int32         `json:"category_id"`
	PaymentMethodID        *uuid.UUID     `json:"payment_method_id"`
	TransactionFrequencyID *int32         `json:"transaction_frequency_id"`
	TransactionTypeID      *int32         `json:"transaction_type_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Name,
		arg.Amount,
		arg.PlannedAmount,
		arg.Date,
		arg.RenewalDate,
		arg.Recurring,
		arg.BudgetID,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.TransactionFrequencyID,
		arg.TransactionTypeID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.Recurring,
		&i.BudgetID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transaction
WHERE id = $1 AND budget_id = $2
`

type DeleteTransactionParams struct {
	ID       uuid.UUID  `json:"id"`
	BudgetID *uuid.UUID `json:"budget_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.BudgetID)
	return err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, name, amount, planned_amount, date, renewal_date, recurring,
       budget_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id
FROM transaction
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.Recurring,
		&i.BudgetID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, type_id, user_id
FROM category
WHERE user_id = $1::uuid OR user_id IS NULL
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context, dollar_1 uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TypeID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentMethods = `-- name: ListPaymentMethods :many
SELECT pm.id, pm.name, pm.payment_type_id, pm.user_id, pt.name AS type_name
FROM payment_methods pm
LEFT JOIN payment_type pt ON pm.payment_type_id = pt.id
WHERE pm.user_id = $1::uuid
ORDER BY pm.name
`

type ListPaymentMethodsRow struct {
	ID            uuid.UUID  `json:"id"`
	Name          string     `json:"name"`
	PaymentTypeID *int32     `json:"payment_type_id"`
	UserID        *uuid.UUID `json:"user_id"`
	TypeName      *string    `json:"type_name"`
}

func (q *Queries) ListPaymentMethods(ctx context.Context, dollar_1 uuid.UUID) ([]ListPaymentMethodsRow, error) {
	rows, err := q.db.Query(ctx, listPaymentMethods, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentMethodsRow
	for rows.Next() {
		var i ListPaymentMethodsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PaymentTypeID,
			&i.UserID,
			&i.TypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionFrequencies = `-- name: ListTransactionFrequencies :many
SELECT id, name FROM transaction_frequency ORDER BY id
`

func (q *Queries) ListTransactionFrequencies(ctx context.Context) ([]TransactionFrequency, error) {
	rows, err := q.db.Query(ctx, listTransactionFrequencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionFrequency
	for rows.Next() {
		var i TransactionFrequency
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionTypes = `-- name: ListTransactionTypes :many
SELECT id, name FROM transaction_type ORDER BY id
`

func (q *Queries) ListTransactionTypes(ctx context.Context) ([]TransactionType, error) {
	rows, err := q.db.Query(ctx, listTransactionTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionType
	for rows.Next() {
		var i TransactionType
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, name, amount, planned_amount, date, renewal_date, recurring,
       budget_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id
FROM transaction
WHERE budget_id = $1::uuid
  AND ($2::int IS NULL OR category_id = $2)
  AND ($3::int IS NULL OR transaction_type_id = $3)
ORDER BY date DESC NULLS LAST
`

type ListTransactionsParams struct {
	BudgetID          uuid.UUID `json:"budget_id"`
	CategoryID        *int32    `json:"category_id"`
	TransactionTypeID *int32    `json:"transaction_type_id"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.BudgetID, arg.CategoryID, arg.TransactionTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.PlannedAmount,
			&i.Date,
			&i.RenewalDate,
			&i.Recurring,
			&i.BudgetID,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.TransactionFrequencyID,
			&i.TransactionTypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transaction
SET name = $2, amount = $3, planned_amount = $4, date = $5, recurring = $6,
    category_id = $7, payment_method_id = $8, transaction_frequency_id = $9, transaction_type_id = $10
WHERE id = $1
RETURNING id, name, amount, planned_amount, date, renewal_date, recurring,
          budget_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id
`

type UpdateTransactionParams struct {
	ID                     uuid.UUID      `json:"id"`
	Name                   *string        `json:"name"`
	Amount                 pgtype.Numeric `json:"amount"`
	PlannedAmount          pgtype.Numeric `json:"planned_amount"`
	Date                   pgtype.Date    `json:"date"`
	Recurring              *bool          `json:"recurring"`
	CategoryID             *int32         `json:"category_id"`
	PaymentMethodID        *uuid.UUID     `json:"payment_method_id"`
	TransactionFrequencyID *int32         `json:"transaction_frequency_id"`
	TransactionTypeID      *int32         `json:"transaction_type_id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.PlannedAmount,
		arg.Date,
		arg.Recurring,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.TransactionFrequencyID,
		arg.TransactionTypeID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.Recurring,
		&i.BudgetID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
	)
	return i, err
}
