// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction_review.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFixedExpenseAlias = `-- name: CreateFixedExpenseAlias :exec
INSERT INTO fixed_expense_alias (fixed_expense_id, alias)
VALUES ($1, $2)
ON CONFLICT (fixed_expense_id, alias) DO NOTHING
`

type CreateFixedExpenseAliasParams struct {
	FixedExpenseID uuid.UUID `json:"fixed_expense_id"`
	Alias          string    `json:"alias"`
}

func (q *Queries) CreateFixedExpenseAlias(ctx context.Context, arg CreateFixedExpenseAliasParams) error {
	_, err := q.db.Exec(ctx, createFixedExpenseAlias, arg.FixedExpenseID, arg.Alias)
	return err
}

const createTransactionReview = `-- name: CreateTransactionReview :one
INSERT INTO transaction_review (budget_period_id, transaction_id, matched_transaction_id, match_score)
VALUES ($1, $2, $3, $4)
ON CONFLICT (transaction_id) DO NOTHING
RETURNING id, budget_period_id, transaction_id, matched_transaction_id, match_score, status, created_at
`

type CreateTransactionReviewParams struct {
	BudgetPeriodID       uuid.UUID      `json:"budget_period_id"`
	TransactionID        uuid.UUID      `json:"transaction_id"`
	MatchedTransactionID uuid.UUID      `json:"matched_transaction_id"`
	MatchScore           pgtype.Numeric `json:"match_score"`
}

type CreateTransactionReviewRow struct {
	ID                   uuid.UUID          `json:"id"`
	BudgetPeriodID       uuid.UUID          `json:"budget_period_id"`
	TransactionID        uuid.UUID          `json:"transaction_id"`
	MatchedTransactionID uuid.UUID          `json:"matched_transaction_id"`
	MatchScore           pgtype.Numeric     `json:"match_score"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTransactionReview(ctx context.Context, arg CreateTransactionReviewParams) (CreateTransactionReviewRow, error) {
	row := q.db.QueryRow(ctx, createTransactionReview,
		arg.BudgetPeriodID,
		arg.TransactionID,
		arg.MatchedTransactionID,
		arg.MatchScore,
	)
	var i CreateTransactionReviewRow
	err := row.Scan(
		&i.ID,
		&i.BudgetPeriodID,
		&i.TransactionID,
		&i.MatchedTransactionID,
		&i.MatchScore,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFixedExpenseAlias = `-- name: DeleteFixedExpenseAlias :exec
DELETE FROM fixed_expense_alias
WHERE fixed_expense_id = $1 AND alias = $2
`

type DeleteFixedExpenseAliasParams struct {
	FixedExpenseID uuid.UUID `json:"fixed_expense_id"`
	Alias          string    `json:"alias"`
}

func (q *Queries) DeleteFixedExpenseAlias(ctx context.Context, arg DeleteFixedExpenseAliasParams) error {
	_, err := q.db.Exec(ctx, deleteFixedExpenseAlias, arg.FixedExpenseID, arg.Alias)
	return err
}

const getConfirmedReviewByMatchedTransaction = `-- name: GetConfirmedReviewByMatchedTransaction :one
SELECT id, budget_period_id, transaction_id, matched_transaction_id, match_score, status, created_at
FROM transaction_review
WHERE matched_transaction_id = $1
  AND status = 'confirmed'
LIMIT 1
`

type GetConfirmedReviewByMatchedTransactionRow struct {
	ID                   uuid.UUID          `json:"id"`
	BudgetPeriodID       uuid.UUID          `json:"budget_period_id"`
	TransactionID        uuid.UUID          `json:"transaction_id"`
	MatchedTransactionID uuid.UUID          `json:"matched_transaction_id"`
	MatchScore           pgtype.Numeric     `json:"match_score"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetConfirmedReviewByMatchedTransaction(ctx context.Context, matchedTransactionID uuid.UUID) (GetConfirmedReviewByMatchedTransactionRow, error) {
	row := q.db.QueryRow(ctx, getConfirmedReviewByMatchedTransaction, matchedTransactionID)
	var i GetConfirmedReviewByMatchedTransactionRow
	err := row.Scan(
		&i.ID,
		&i.BudgetPeriodID,
		&i.TransactionID,
		&i.MatchedTransactionID,
		&i.MatchScore,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getFixedExpenseByAlias = `-- name: GetFixedExpenseByAlias :one
SELECT fe.id, fe.budget_profile_id, fe.name, fe.planned_amount, fe.category_id,
       fe.payment_method_id, fe.day_of_month, fe.is_active, fe.created_at
FROM fixed_expense fe
JOIN fixed_expense_alias fea ON fea.fixed_expense_id = fe.id
WHERE fea.alias = $1
  AND fe.budget_profile_id = $2
  AND fe.is_active = TRUE
LIMIT 1
`

type GetFixedExpenseByAliasParams struct {
	Alias           string    `json:"alias"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

type GetFixedExpenseByAliasRow struct {
	ID              uuid.UUID          `json:"id"`
	BudgetProfileID uuid.UUID          `json:"budget_profile_id"`
	Name            string             `json:"name"`
	PlannedAmount   pgtype.Numeric     `json:"planned_amount"`
	CategoryID      *int32             `json:"category_id"`
	PaymentMethodID *uuid.UUID         `json:"payment_method_id"`
	DayOfMonth      int32              `json:"day_of_month"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetFixedExpenseByAlias(ctx context.Context, arg GetFixedExpenseByAliasParams) (GetFixedExpenseByAliasRow, error) {
	row := q.db.QueryRow(ctx, getFixedExpenseByAlias, arg.Alias, arg.BudgetProfileID)
	var i GetFixedExpenseByAliasRow
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.Name,
		&i.PlannedAmount,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.DayOfMonth,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionReview = `-- name: GetTransactionReview :one
SELECT id, budget_period_id, transaction_id, matched_transaction_id, match_score, status, created_at
FROM transaction_review
WHERE id = $1
LIMIT 1
`

type GetTransactionReviewRow struct {
	ID                   uuid.UUID          `json:"id"`
	BudgetPeriodID       uuid.UUID          `json:"budget_period_id"`
	TransactionID        uuid.UUID          `json:"transaction_id"`
	MatchedTransactionID uuid.UUID          `json:"matched_transaction_id"`
	MatchScore           pgtype.Numeric     `json:"match_score"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetTransactionReview(ctx context.Context, id uuid.UUID) (GetTransactionReviewRow, error) {
	row := q.db.QueryRow(ctx, getTransactionReview, id)
	var i GetTransactionReviewRow
	err := row.Scan(
		&i.ID,
		&i.BudgetPeriodID,
		&i.TransactionID,
		&i.MatchedTransactionID,
		&i.MatchScore,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listFixedExpenseAliases = `-- name: ListFixedExpenseAliases :many
SELECT alias FROM fixed_expense_alias WHERE fixed_expense_id = $1
`

func (q *Queries) ListFixedExpenseAliases(ctx context.Context, fixedExpenseID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listFixedExpenseAliases, fixedExpenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var alias string
		if err := rows.Scan(&alias); err != nil {
			return nil, err
		}
		items = append(items, alias)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionReviews = `-- name: ListTransactionReviews :many
SELECT
    tr.id, tr.budget_period_id, tr.transaction_id, tr.matched_transaction_id,
    tr.match_score, tr.status, tr.created_at,
    t.name  AS transaction_name,
    t.amount AS transaction_amount,
    mt.name AS matched_transaction_name
FROM transaction_review tr
JOIN transaction t  ON t.id  = tr.transaction_id
JOIN transaction mt ON mt.id = tr.matched_transaction_id
JOIN budget_period bp ON bp.id = tr.budget_period_id
WHERE bp.budget_profile_id = $1
  AND bp.is_archived = FALSE
  AND tr.status != 'dismissed'
ORDER BY tr.match_score DESC
`

type ListTransactionReviewsRow struct {
	ID                     uuid.UUID          `json:"id"`
	BudgetPeriodID         uuid.UUID          `json:"budget_period_id"`
	TransactionID          uuid.UUID          `json:"transaction_id"`
	MatchedTransactionID   uuid.UUID          `json:"matched_transaction_id"`
	MatchScore             pgtype.Numeric     `json:"match_score"`
	Status                 string             `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	TransactionName        *string            `json:"transaction_name"`
	TransactionAmount      pgtype.Numeric     `json:"transaction_amount"`
	MatchedTransactionName *string            `json:"matched_transaction_name"`
}

// ListTransactionReviews joins transaction twice: once for the
// flagged/imported transaction (t), once for the matched Fixed-type
// transaction (mt) — which may be spawned from a FixedExpense template or a
// SavingsSource, no distinction needed since both are just transactions.
// Returns pending and confirmed reviews (not dismissed). The frontend filters
// by status to separate the To-Review queue from already-linked transactions.
func (q *Queries) ListTransactionReviews(ctx context.Context, budgetProfileID uuid.UUID) ([]ListTransactionReviewsRow, error) {
	rows, err := q.db.Query(ctx, listTransactionReviews, budgetProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionReviewsRow
	for rows.Next() {
		var i ListTransactionReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.BudgetPeriodID,
			&i.TransactionID,
			&i.MatchedTransactionID,
			&i.MatchScore,
			&i.Status,
			&i.CreatedAt,
			&i.TransactionName,
			&i.TransactionAmount,
			&i.MatchedTransactionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetConfirmedReviewByMatchedTransaction = `-- name: ResetConfirmedReviewByMatchedTransaction :exec
UPDATE transaction_review
SET status = 'pending'
WHERE matched_transaction_id = $1
  AND status = 'confirmed'
`

func (q *Queries) ResetConfirmedReviewByMatchedTransaction(ctx context.Context, matchedTransactionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetConfirmedReviewByMatchedTransaction, matchedTransactionID)
	return err
}

const updateTransactionReviewStatus = `-- name: UpdateTransactionReviewStatus :exec
UPDATE transaction_review SET status = $2 WHERE id = $1
`

type UpdateTransactionReviewStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTransactionReviewStatus(ctx context.Context, arg UpdateTransactionReviewStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransactionReviewStatus, arg.ID, arg.Status)
	return err
}

const upsertTransactionReview = `-- name: UpsertTransactionReview :one
INSERT INTO transaction_review (budget_period_id, transaction_id, matched_transaction_id, match_score, status)
VALUES ($1, $2, $3, $4, 'pending')
ON CONFLICT (transaction_id) DO UPDATE SET
    matched_transaction_id = EXCLUDED.matched_transaction_id,
    match_score            = EXCLUDED.match_score,
    status                 = 'pending'
RETURNING id, budget_period_id, transaction_id, matched_transaction_id, match_score, status, created_at
`

type UpsertTransactionReviewParams struct {
	BudgetPeriodID       uuid.UUID      `json:"budget_period_id"`
	TransactionID        uuid.UUID      `json:"transaction_id"`
	MatchedTransactionID uuid.UUID      `json:"matched_transaction_id"`
	MatchScore           pgtype.Numeric `json:"match_score"`
}

type UpsertTransactionReviewRow struct {
	ID                   uuid.UUID          `json:"id"`
	BudgetPeriodID       uuid.UUID          `json:"budget_period_id"`
	TransactionID        uuid.UUID          `json:"transaction_id"`
	MatchedTransactionID uuid.UUID          `json:"matched_transaction_id"`
	MatchScore           pgtype.Numeric     `json:"match_score"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertTransactionReview(ctx context.Context, arg UpsertTransactionReviewParams) (UpsertTransactionReviewRow, error) {
	row := q.db.QueryRow(ctx, upsertTransactionReview,
		arg.BudgetPeriodID,
		arg.TransactionID,
		arg.MatchedTransactionID,
		arg.MatchScore,
	)
	var i UpsertTransactionReviewRow
	err := row.Scan(
		&i.ID,
		&i.BudgetPeriodID,
		&i.TransactionID,
		&i.MatchedTransactionID,
		&i.MatchScore,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
