// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO category (name, user_id, color)
VALUES ($1, $2::uuid, $3)
RETURNING id, name, type_id, is_system, user_id, color
`

type CreateCategoryParams struct {
	Name   string    `json:"name"`
	UserID uuid.UUID `json:"user_id"`
	Color  string    `json:"color"`
}

type CreateCategoryRow struct {
	ID       int32      `json:"id"`
	Name     string     `json:"name"`
	TypeID   *int32     `json:"type_id"`
	IsSystem bool       `json:"is_system"`
	UserID   *uuid.UUID `json:"user_id"`
	Color    string     `json:"color"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.UserID, arg.Color)
	var i CreateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TypeID,
		&i.IsSystem,
		&i.UserID,
		&i.Color,
	)
	return i, err
}

const createPaymentMethod = `-- name: CreatePaymentMethod :one
INSERT INTO payment_methods (name, payment_type_id, user_id, budget_person_id, color)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, payment_type_id, user_id, is_active, budget_person_id, color
`

type CreatePaymentMethodParams struct {
	Name           string     `json:"name"`
	PaymentTypeID  *int32     `json:"payment_type_id"`
	UserID         *uuid.UUID `json:"user_id"`
	BudgetPersonID *int32     `json:"budget_person_id"`
	Color          string     `json:"color"`
}

func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, createPaymentMethod,
		arg.Name,
		arg.PaymentTypeID,
		arg.UserID,
		arg.BudgetPersonID,
		arg.Color,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PaymentTypeID,
		&i.UserID,
		&i.IsActive,
		&i.BudgetPersonID,
		&i.Color,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transaction (
    name, amount, planned_amount, date, renewal_date, recurring,
    budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
    fixed_expense_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, name, amount, planned_amount, date, renewal_date, recurring,
          budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
          is_paid, paid_date, fixed_expense_id
`

type CreateTransactionParams struct {
	Name                   *string        `json:"name"`
	Amount                 pgtype.Numeric `json:"amount"`
	PlannedAmount          pgtype.Numeric `json:"planned_amount"`
	Date                   pgtype.Date    `json:"date"`
	RenewalDate            pgtype.Date    `json:"renewal_date"`
	Recurring              *bool          `json:"recurring"`
	BudgetPeriodID         *uuid.UUID     `json:"budget_period_id"`
	CategoryID             *int32         `json:"category_id"`
	PaymentMethodID        *uuid.UUID     `json:"payment_method_id"`
	TransactionFrequencyID *int32         `json:"transaction_frequency_id"`
	TransactionTypeID      *int32         `json:"transaction_type_id"`
	FixedExpenseID         *uuid.UUID     `json:"fixed_expense_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Name,
		arg.Amount,
		arg.PlannedAmount,
		arg.Date,
		arg.RenewalDate,
		arg.Recurring,
		arg.BudgetPeriodID,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.TransactionFrequencyID,
		arg.TransactionTypeID,
		arg.FixedExpenseID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.Recurring,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
	)
	return i, err
}

const deleteCategoryAndReassign = `-- name: DeleteCategoryAndReassign :exec
WITH moved AS (
    UPDATE transaction SET category_id = $3
    WHERE category_id = $1
)
UPDATE category
SET is_active = FALSE
WHERE category.id = $1 AND category.user_id = $2::uuid AND category.is_system = FALSE
`

type DeleteCategoryAndReassignParams struct {
	ID            int32     `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	ReplacementID *int32    `json:"replacement_id"`
}

// Reassigns all transactions with this category to the replacement, then soft-deletes.
// No budget scoping: categories are user-scoped so reassignment spans all periods.
func (q *Queries) DeleteCategoryAndReassign(ctx context.Context, arg DeleteCategoryAndReassignParams) error {
	_, err := q.db.Exec(ctx, deleteCategoryAndReassign, arg.ID, arg.UserID, arg.ReplacementID)
	return err
}

const deletePaymentMethodAndReassign = `-- name: DeletePaymentMethodAndReassign :exec
WITH moved AS (
    UPDATE transaction SET payment_method_id = $3::uuid
    WHERE payment_method_id = $1::uuid
      AND budget_period_id IN (
        SELECT bp.id FROM budget_period bp WHERE bp.budget_profile_id = $4::uuid
      )
)
UPDATE payment_methods
SET is_active = FALSE
WHERE payment_methods.id = $1::uuid AND payment_methods.user_id = $2::uuid
`

type DeletePaymentMethodAndReassignParams struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	ReplacementID   uuid.UUID `json:"replacement_id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

// Reassigns all transactions referencing this method within the profile's periods, then soft-deletes.
func (q *Queries) DeletePaymentMethodAndReassign(ctx context.Context, arg DeletePaymentMethodAndReassignParams) error {
	_, err := q.db.Exec(ctx, deletePaymentMethodAndReassign,
		arg.ID,
		arg.UserID,
		arg.ReplacementID,
		arg.BudgetProfileID,
	)
	return err
}

const deleteSavingsSourceTransactions = `-- name: DeleteSavingsSourceTransactions :exec
DELETE FROM transaction
WHERE budget_period_id IN (
    SELECT id FROM budget_period
    WHERE budget_profile_id = $1::uuid AND is_archived = FALSE
)
AND name = $2
AND payment_method_id = $3::uuid
AND category_id = $4
`

type DeleteSavingsSourceTransactionsParams struct {
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
	Name            *string   `json:"name"`
	PaymentMethodID uuid.UUID `json:"payment_method_id"`
	CategoryID      *int32    `json:"category_id"`
}

// Deletes auto-created savings transactions when a savings source is removed.
// Matches by name, payment method, and category within non-archived periods.
func (q *Queries) DeleteSavingsSourceTransactions(ctx context.Context, arg DeleteSavingsSourceTransactionsParams) error {
	_, err := q.db.Exec(ctx, deleteSavingsSourceTransactions,
		arg.BudgetProfileID,
		arg.Name,
		arg.PaymentMethodID,
		arg.CategoryID,
	)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transaction
WHERE id = $1 AND budget_period_id = $2
`

type DeleteTransactionParams struct {
	ID             uuid.UUID  `json:"id"`
	BudgetPeriodID *uuid.UUID `json:"budget_period_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.BudgetPeriodID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, type_id, is_system, user_id, color
FROM category
WHERE id = $1
LIMIT 1
`

type GetCategoryRow struct {
	ID       int32      `json:"id"`
	Name     string     `json:"name"`
	TypeID   *int32     `json:"type_id"`
	IsSystem bool       `json:"is_system"`
	UserID   *uuid.UUID `json:"user_id"`
	Color    string     `json:"color"`
}

func (q *Queries) GetCategory(ctx context.Context, id int32) (GetCategoryRow, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i GetCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TypeID,
		&i.IsSystem,
		&i.UserID,
		&i.Color,
	)
	return i, err
}

const getPaymentMethod = `-- name: GetPaymentMethod :one
SELECT id, name, payment_type_id, user_id, is_active, budget_person_id, color
FROM payment_methods
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPaymentMethod(ctx context.Context, id uuid.UUID) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethod, id)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PaymentTypeID,
		&i.UserID,
		&i.IsActive,
		&i.BudgetPersonID,
		&i.Color,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, name, amount, planned_amount, date, renewal_date, recurring,
       budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
       is_paid, paid_date, fixed_expense_id
FROM transaction
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.Recurring,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, type_id, is_system, user_id, color
FROM category
WHERE (user_id = $1::uuid AND is_active = TRUE) OR user_id IS NULL
ORDER BY name
`

type ListCategoriesRow struct {
	ID       int32      `json:"id"`
	Name     string     `json:"name"`
	TypeID   *int32     `json:"type_id"`
	IsSystem bool       `json:"is_system"`
	UserID   *uuid.UUID `json:"user_id"`
	Color    string     `json:"color"`
}

func (q *Queries) ListCategories(ctx context.Context, dollar_1 uuid.UUID) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TypeID,
			&i.IsSystem,
			&i.UserID,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentMethods = `-- name: ListPaymentMethods :many
SELECT pm.id, pm.name, pm.payment_type_id, pm.user_id, pt.name AS type_name, pm.budget_person_id, pm.color
FROM payment_methods pm
LEFT JOIN payment_type pt ON pm.payment_type_id = pt.id
WHERE pm.budget_person_id IN (
    SELECT id FROM budget_to_profile_mapping WHERE budget_profile_id = $1::uuid
)
AND pm.is_active = TRUE
ORDER BY pm.name
`

type ListPaymentMethodsRow struct {
	ID             uuid.UUID  `json:"id"`
	Name           string     `json:"name"`
	PaymentTypeID  *int32     `json:"payment_type_id"`
	UserID         *uuid.UUID `json:"user_id"`
	TypeName       *string    `json:"type_name"`
	BudgetPersonID *int32     `json:"budget_person_id"`
	Color          string     `json:"color"`
}

func (q *Queries) ListPaymentMethods(ctx context.Context, dollar_1 uuid.UUID) ([]ListPaymentMethodsRow, error) {
	rows, err := q.db.Query(ctx, listPaymentMethods, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentMethodsRow
	for rows.Next() {
		var i ListPaymentMethodsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PaymentTypeID,
			&i.UserID,
			&i.TypeName,
			&i.BudgetPersonID,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionFrequencies = `-- name: ListTransactionFrequencies :many
SELECT id, name FROM transaction_frequency ORDER BY id
`

func (q *Queries) ListTransactionFrequencies(ctx context.Context) ([]TransactionFrequency, error) {
	rows, err := q.db.Query(ctx, listTransactionFrequencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionFrequency
	for rows.Next() {
		var i TransactionFrequency
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionTypes = `-- name: ListTransactionTypes :many
SELECT id, name FROM transaction_type ORDER BY id
`

func (q *Queries) ListTransactionTypes(ctx context.Context) ([]TransactionType, error) {
	rows, err := q.db.Query(ctx, listTransactionTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionType
	for rows.Next() {
		var i TransactionType
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, name, amount, planned_amount, date, renewal_date, recurring,
       budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
       is_paid, paid_date, fixed_expense_id
FROM transaction
WHERE budget_period_id = $1::uuid
  AND ($2::int IS NULL OR category_id = $2)
  AND ($3::int IS NULL OR transaction_type_id = $3)
ORDER BY date DESC NULLS LAST
`

type ListTransactionsParams struct {
	BudgetPeriodID    uuid.UUID `json:"budget_period_id"`
	CategoryID        *int32    `json:"category_id"`
	TransactionTypeID *int32    `json:"transaction_type_id"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.BudgetPeriodID, arg.CategoryID, arg.TransactionTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.PlannedAmount,
			&i.Date,
			&i.RenewalDate,
			&i.Recurring,
			&i.BudgetPeriodID,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.TransactionFrequencyID,
			&i.TransactionTypeID,
			&i.IsPaid,
			&i.PaidDate,
			&i.FixedExpenseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTransactionAsPaid = `-- name: MarkTransactionAsPaid :one
UPDATE transaction
SET is_paid = TRUE,
    paid_date = $1::date,
    amount = $2
WHERE id = $3::uuid
  AND budget_period_id = $4::uuid
RETURNING id, name, amount, planned_amount, date, renewal_date, recurring,
          budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
          is_paid, paid_date, fixed_expense_id
`

type MarkTransactionAsPaidParams struct {
	PaidDate       pgtype.Date    `json:"paid_date"`
	Amount         pgtype.Numeric `json:"amount"`
	ID             uuid.UUID      `json:"id"`
	BudgetPeriodID uuid.UUID      `json:"budget_period_id"`
}

func (q *Queries) MarkTransactionAsPaid(ctx context.Context, arg MarkTransactionAsPaidParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, markTransactionAsPaid,
		arg.PaidDate,
		arg.Amount,
		arg.ID,
		arg.BudgetPeriodID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.Recurring,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE category
SET name = $1, color = $2
WHERE id = $3 AND user_id = $4::uuid AND is_system = FALSE
RETURNING id, name, type_id, is_system, user_id, color
`

type UpdateCategoryParams struct {
	Name   string    `json:"name"`
	Color  string    `json:"color"`
	ID     int32     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type UpdateCategoryRow struct {
	ID       int32      `json:"id"`
	Name     string     `json:"name"`
	TypeID   *int32     `json:"type_id"`
	IsSystem bool       `json:"is_system"`
	UserID   *uuid.UUID `json:"user_id"`
	Color    string     `json:"color"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Color,
		arg.ID,
		arg.UserID,
	)
	var i UpdateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TypeID,
		&i.IsSystem,
		&i.UserID,
		&i.Color,
	)
	return i, err
}

const updatePaymentMethod = `-- name: UpdatePaymentMethod :one
UPDATE payment_methods
SET name = $1, color = $2
WHERE id = $3 AND user_id = $4::uuid
RETURNING id, name, payment_type_id, user_id, is_active, budget_person_id, color
`

type UpdatePaymentMethodParams struct {
	Name   string    `json:"name"`
	Color  string    `json:"color"`
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, updatePaymentMethod,
		arg.Name,
		arg.Color,
		arg.ID,
		arg.UserID,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PaymentTypeID,
		&i.UserID,
		&i.IsActive,
		&i.BudgetPersonID,
		&i.Color,
	)
	return i, err
}

const updateSystemCategoryColor = `-- name: UpdateSystemCategoryColor :one
UPDATE category
SET color = $1
WHERE id = $2 AND is_system = TRUE
RETURNING id, name, type_id, is_system, user_id, color
`

type UpdateSystemCategoryColorParams struct {
	Color string `json:"color"`
	ID    int32  `json:"id"`
}

type UpdateSystemCategoryColorRow struct {
	ID       int32      `json:"id"`
	Name     string     `json:"name"`
	TypeID   *int32     `json:"type_id"`
	IsSystem bool       `json:"is_system"`
	UserID   *uuid.UUID `json:"user_id"`
	Color    string     `json:"color"`
}

func (q *Queries) UpdateSystemCategoryColor(ctx context.Context, arg UpdateSystemCategoryColorParams) (UpdateSystemCategoryColorRow, error) {
	row := q.db.QueryRow(ctx, updateSystemCategoryColor, arg.Color, arg.ID)
	var i UpdateSystemCategoryColorRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TypeID,
		&i.IsSystem,
		&i.UserID,
		&i.Color,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transaction
SET name = $2, amount = $3, planned_amount = $4, date = $5, recurring = $6,
    category_id = $7, payment_method_id = $8, transaction_frequency_id = $9, transaction_type_id = $10
WHERE id = $1
RETURNING id, name, amount, planned_amount, date, renewal_date, recurring,
          budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
          is_paid, paid_date, fixed_expense_id
`

type UpdateTransactionParams struct {
	ID                     uuid.UUID      `json:"id"`
	Name                   *string        `json:"name"`
	Amount                 pgtype.Numeric `json:"amount"`
	PlannedAmount          pgtype.Numeric `json:"planned_amount"`
	Date                   pgtype.Date    `json:"date"`
	Recurring              *bool          `json:"recurring"`
	CategoryID             *int32         `json:"category_id"`
	PaymentMethodID        *uuid.UUID     `json:"payment_method_id"`
	TransactionFrequencyID *int32         `json:"transaction_frequency_id"`
	TransactionTypeID      *int32         `json:"transaction_type_id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.PlannedAmount,
		arg.Date,
		arg.Recurring,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.TransactionFrequencyID,
		arg.TransactionTypeID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.Recurring,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
	)
	return i, err
}
