// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_account (user_id, oauth_name, account_id, account_email)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, oauth_name, account_id, account_email
`

type CreateOAuthAccountParams struct {
	UserID       uuid.UUID `json:"user_id"`
	OauthName    string    `json:"oauth_name"`
	AccountID    string    `json:"account_id"`
	AccountEmail string    `json:"account_email"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.UserID,
		arg.OauthName,
		arg.AccountID,
		arg.AccountEmail,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OauthName,
		&i.AccountID,
		&i.AccountEmail,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, hashed_password, first_name, last_name, country_code, state_code, language, currency)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at,
          country_code, state_code, filing_status, tax_payment_frequency, language, currency
`

type CreateUserParams struct {
	Email          string  `json:"email"`
	HashedPassword *string `json:"hashed_password"`
	FirstName      *string `json:"first_name"`
	LastName       *string `json:"last_name"`
	CountryCode    *string `json:"country_code"`
	StateCode      *string `json:"state_code"`
	Language       string  `json:"language"`
	Currency       string  `json:"currency"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.HashedPassword,
		arg.FirstName,
		arg.LastName,
		arg.CountryCode,
		arg.StateCode,
		arg.Language,
		arg.Currency,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.CountryCode,
		&i.StateCode,
		&i.FilingStatus,
		&i.TaxPaymentFrequency,
		&i.Language,
		&i.Currency,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, user_id, oauth_name, account_id, account_email
FROM oauth_account
WHERE oauth_name = $1 AND account_id = $2
LIMIT 1
`

type GetOAuthAccountParams struct {
	OauthName string `json:"oauth_name"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, arg.OauthName, arg.AccountID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OauthName,
		&i.AccountID,
		&i.AccountEmail,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at,
       country_code, state_code, filing_status, tax_payment_frequency, language, currency
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.CountryCode,
		&i.StateCode,
		&i.FilingStatus,
		&i.TaxPaymentFrequency,
		&i.Language,
		&i.Currency,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at,
       country_code, state_code, filing_status, tax_payment_frequency, language, currency
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.CountryCode,
		&i.StateCode,
		&i.FilingStatus,
		&i.TaxPaymentFrequency,
		&i.Language,
		&i.Currency,
	)
	return i, err
}

const listCountryFeatures = `-- name: ListCountryFeatures :many
SELECT country_code, feature_name, is_enabled
FROM country_features
ORDER BY country_code, feature_name
`

func (q *Queries) ListCountryFeatures(ctx context.Context) ([]CountryFeature, error) {
	rows, err := q.db.Query(ctx, listCountryFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountryFeature
	for rows.Next() {
		var i CountryFeature
		if err := rows.Scan(&i.CountryCode, &i.FeatureName, &i.IsEnabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledCountries = `-- name: ListEnabledCountries :many
SELECT code, name, is_enabled
FROM countries
WHERE is_enabled = TRUE
ORDER BY name
`

type ListEnabledCountriesRow struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	IsEnabled bool   `json:"is_enabled"`
}

func (q *Queries) ListEnabledCountries(ctx context.Context) ([]ListEnabledCountriesRow, error) {
	rows, err := q.db.Query(ctx, listEnabledCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledCountriesRow
	for rows.Next() {
		var i ListEnabledCountriesRow
		if err := rows.Scan(&i.Code, &i.Name, &i.IsEnabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name            = $1,
    last_name             = $2,
    country_code          = $3,
    state_code            = $4,
    filing_status         = $5,
    tax_payment_frequency = $6,
    language              = $7,
    currency              = $8
WHERE id = $9
RETURNING id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at,
          country_code, state_code, filing_status, tax_payment_frequency, language, currency
`

type UpdateUserParams struct {
	FirstName           *string   `json:"first_name"`
	LastName            *string   `json:"last_name"`
	CountryCode         *string   `json:"country_code"`
	StateCode           *string   `json:"state_code"`
	FilingStatus        string    `json:"filing_status"`
	TaxPaymentFrequency int32     `json:"tax_payment_frequency"`
	Language            string    `json:"language"`
	Currency            string    `json:"currency"`
	ID                  uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.CountryCode,
		arg.StateCode,
		arg.FilingStatus,
		arg.TaxPaymentFrequency,
		arg.Language,
		arg.Currency,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.CountryCode,
		&i.StateCode,
		&i.FilingStatus,
		&i.TaxPaymentFrequency,
		&i.Language,
		&i.Currency,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET hashed_password = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID             uuid.UUID `json:"id"`
	HashedPassword *string   `json:"hashed_password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.HashedPassword)
	return err
}
