// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_account (user_id, oauth_name, account_id, account_email)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, oauth_name, account_id, account_email
`

type CreateOAuthAccountParams struct {
	UserID       uuid.UUID `json:"user_id"`
	OauthName    string    `json:"oauth_name"`
	AccountID    string    `json:"account_id"`
	AccountEmail string    `json:"account_email"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.UserID,
		arg.OauthName,
		arg.AccountID,
		arg.AccountEmail,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OauthName,
		&i.AccountID,
		&i.AccountEmail,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, hashed_password, first_name, last_name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at
`

type CreateUserParams struct {
	Email          string  `json:"email"`
	HashedPassword *string `json:"hashed_password"`
	FirstName      *string `json:"first_name"`
	LastName       *string `json:"last_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.HashedPassword,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, user_id, oauth_name, account_id, account_email
FROM oauth_account
WHERE oauth_name = $1 AND account_id = $2
LIMIT 1
`

type GetOAuthAccountParams struct {
	OauthName string `json:"oauth_name"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, arg.OauthName, arg.AccountID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OauthName,
		&i.AccountID,
		&i.AccountEmail,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name = $2, last_name = $3
WHERE id = $1
RETURNING id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at
`

type UpdateUserParams struct {
	ID        uuid.UUID `json:"id"`
	FirstName *string   `json:"first_name"`
	LastName  *string   `json:"last_name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.FirstName, arg.LastName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET hashed_password = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID             uuid.UUID `json:"id"`
	HashedPassword *string   `json:"hashed_password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.HashedPassword)
	return err
}
