name: CI

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...

      - name: Migrate dev
        if: github.ref == 'refs/heads/develop'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}
        run: go run ./cmd/migrate up
